module

public import FKLMeta.Walk
public import FKLBridge.Dyadic

/-! Every row of `IndexedCertificateRows.dyadic` satisfies a raw test `q`, checked by one walk over the
literal parts `CertificateData.Part###.rows`. Generated by `gen_walks.py`. -/

@[expose] public section

namespace FKLMeta.DyWalk

open MatrixBounds.Numeric
set_option maxRecDepth 100000

/-- Walk all 60 literal parts. -/
def allRows (q : Nat → DyadicRow → Bool) : Bool :=
  Bool.and (walk q CertificateData.Part000.rows 0)
    (Bool.and (walk q CertificateData.Part001.rows 256)
    (Bool.and (walk q CertificateData.Part002.rows 512)
    (Bool.and (walk q CertificateData.Part003.rows 768)
    (Bool.and (walk q CertificateData.Part004.rows 1024)
    (Bool.and (walk q CertificateData.Part005.rows 1280)
    (Bool.and (walk q CertificateData.Part006.rows 1536)
    (Bool.and (walk q CertificateData.Part007.rows 1792)
    (Bool.and (walk q CertificateData.Part008.rows 2048)
    (Bool.and (walk q CertificateData.Part009.rows 2304)
    (Bool.and (walk q CertificateData.Part010.rows 2560)
    (Bool.and (walk q CertificateData.Part011.rows 2816)
    (Bool.and (walk q CertificateData.Part012.rows 3072)
    (Bool.and (walk q CertificateData.Part013.rows 3328)
    (Bool.and (walk q CertificateData.Part014.rows 3584)
    (Bool.and (walk q CertificateData.Part015.rows 3840)
    (Bool.and (walk q CertificateData.Part016.rows 4096)
    (Bool.and (walk q CertificateData.Part017.rows 4352)
    (Bool.and (walk q CertificateData.Part018.rows 4608)
    (Bool.and (walk q CertificateData.Part019.rows 4864)
    (Bool.and (walk q CertificateData.Part020.rows 5120)
    (Bool.and (walk q CertificateData.Part021.rows 5376)
    (Bool.and (walk q CertificateData.Part022.rows 5632)
    (Bool.and (walk q CertificateData.Part023.rows 5888)
    (Bool.and (walk q CertificateData.Part024.rows 6144)
    (Bool.and (walk q CertificateData.Part025.rows 6400)
    (Bool.and (walk q CertificateData.Part026.rows 6656)
    (Bool.and (walk q CertificateData.Part027.rows 6912)
    (Bool.and (walk q CertificateData.Part028.rows 7168)
    (Bool.and (walk q CertificateData.Part029.rows 7424)
    (Bool.and (walk q CertificateData.Part030.rows 7680)
    (Bool.and (walk q CertificateData.Part031.rows 7936)
    (Bool.and (walk q CertificateData.Part032.rows 8192)
    (Bool.and (walk q CertificateData.Part033.rows 8448)
    (Bool.and (walk q CertificateData.Part034.rows 8704)
    (Bool.and (walk q CertificateData.Part035.rows 8960)
    (Bool.and (walk q CertificateData.Part036.rows 9216)
    (Bool.and (walk q CertificateData.Part037.rows 9472)
    (Bool.and (walk q CertificateData.Part038.rows 9728)
    (Bool.and (walk q CertificateData.Part039.rows 9984)
    (Bool.and (walk q CertificateData.Part040.rows 10240)
    (Bool.and (walk q CertificateData.Part041.rows 10496)
    (Bool.and (walk q CertificateData.Part042.rows 10752)
    (Bool.and (walk q CertificateData.Part043.rows 11008)
    (Bool.and (walk q CertificateData.Part044.rows 11264)
    (Bool.and (walk q CertificateData.Part045.rows 11520)
    (Bool.and (walk q CertificateData.Part046.rows 11776)
    (Bool.and (walk q CertificateData.Part047.rows 12032)
    (Bool.and (walk q CertificateData.Part048.rows 12288)
    (Bool.and (walk q CertificateData.Part049.rows 12544)
    (Bool.and (walk q CertificateData.Part050.rows 12800)
    (Bool.and (walk q CertificateData.Part051.rows 13056)
    (Bool.and (walk q CertificateData.Part052.rows 13312)
    (Bool.and (walk q CertificateData.Part053.rows 13568)
    (Bool.and (walk q CertificateData.Part054.rows 13824)
    (Bool.and (walk q CertificateData.Part055.rows 14080)
    (Bool.and (walk q CertificateData.Part056.rows 14336)
    (Bool.and (walk q CertificateData.Part057.rows 14592)
    (Bool.and (walk q CertificateData.Part058.rows 14848)
    (walk q CertificateData.Part059.rows 15104)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem allRows_sound (q : Nat → DyadicRow → Bool) (h : allRows q = true) :
    ∀ r : Fin 15279, q r.val (IndexedCertificateRows.dyadic r).val = true := by
  simp only [allRows, Bool.and_eq_true] at h
  obtain ⟨h000, h001, h002, h003, h004, h005, h006, h007, h008, h009, h010, h011, h012, h013, h014, h015, h016, h017, h018, h019, h020, h021, h022, h023, h024, h025, h026, h027, h028, h029, h030, h031, h032, h033, h034, h035, h036, h037, h038, h039, h040, h041, h042, h043, h044, h045, h046, h047, h048, h049, h050, h051, h052, h053, h054, h055, h056, h057, h058, h059⟩ := h
  have P0 : ∀ r < 0, ∀ hr : r < 15279, q r (IndexedCertificateRows.dyadic ⟨r, hr⟩).val = true :=
    FKLBridge.Rows.range_zero
  have P1 := FKLBridge.Rows.range_step 0 256 256 rfl P0 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch000 j hj hr]; exact walk_sound q _ 0 h000 j _)
  have P2 := FKLBridge.Rows.range_step 256 256 512 rfl P1 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch001 j hj hr]; exact walk_sound q _ 256 h001 j _)
  have P3 := FKLBridge.Rows.range_step 512 256 768 rfl P2 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch002 j hj hr]; exact walk_sound q _ 512 h002 j _)
  have P4 := FKLBridge.Rows.range_step 768 256 1024 rfl P3 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch003 j hj hr]; exact walk_sound q _ 768 h003 j _)
  have P5 := FKLBridge.Rows.range_step 1024 256 1280 rfl P4 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch004 j hj hr]; exact walk_sound q _ 1024 h004 j _)
  have P6 := FKLBridge.Rows.range_step 1280 256 1536 rfl P5 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch005 j hj hr]; exact walk_sound q _ 1280 h005 j _)
  have P7 := FKLBridge.Rows.range_step 1536 256 1792 rfl P6 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch006 j hj hr]; exact walk_sound q _ 1536 h006 j _)
  have P8 := FKLBridge.Rows.range_step 1792 256 2048 rfl P7 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch007 j hj hr]; exact walk_sound q _ 1792 h007 j _)
  have P9 := FKLBridge.Rows.range_step 2048 256 2304 rfl P8 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch008 j hj hr]; exact walk_sound q _ 2048 h008 j _)
  have P10 := FKLBridge.Rows.range_step 2304 256 2560 rfl P9 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch009 j hj hr]; exact walk_sound q _ 2304 h009 j _)
  have P11 := FKLBridge.Rows.range_step 2560 256 2816 rfl P10 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch010 j hj hr]; exact walk_sound q _ 2560 h010 j _)
  have P12 := FKLBridge.Rows.range_step 2816 256 3072 rfl P11 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch011 j hj hr]; exact walk_sound q _ 2816 h011 j _)
  have P13 := FKLBridge.Rows.range_step 3072 256 3328 rfl P12 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch012 j hj hr]; exact walk_sound q _ 3072 h012 j _)
  have P14 := FKLBridge.Rows.range_step 3328 256 3584 rfl P13 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch013 j hj hr]; exact walk_sound q _ 3328 h013 j _)
  have P15 := FKLBridge.Rows.range_step 3584 256 3840 rfl P14 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch014 j hj hr]; exact walk_sound q _ 3584 h014 j _)
  have P16 := FKLBridge.Rows.range_step 3840 256 4096 rfl P15 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch015 j hj hr]; exact walk_sound q _ 3840 h015 j _)
  have P17 := FKLBridge.Rows.range_step 4096 256 4352 rfl P16 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch016 j hj hr]; exact walk_sound q _ 4096 h016 j _)
  have P18 := FKLBridge.Rows.range_step 4352 256 4608 rfl P17 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch017 j hj hr]; exact walk_sound q _ 4352 h017 j _)
  have P19 := FKLBridge.Rows.range_step 4608 256 4864 rfl P18 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch018 j hj hr]; exact walk_sound q _ 4608 h018 j _)
  have P20 := FKLBridge.Rows.range_step 4864 256 5120 rfl P19 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch019 j hj hr]; exact walk_sound q _ 4864 h019 j _)
  have P21 := FKLBridge.Rows.range_step 5120 256 5376 rfl P20 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch020 j hj hr]; exact walk_sound q _ 5120 h020 j _)
  have P22 := FKLBridge.Rows.range_step 5376 256 5632 rfl P21 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch021 j hj hr]; exact walk_sound q _ 5376 h021 j _)
  have P23 := FKLBridge.Rows.range_step 5632 256 5888 rfl P22 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch022 j hj hr]; exact walk_sound q _ 5632 h022 j _)
  have P24 := FKLBridge.Rows.range_step 5888 256 6144 rfl P23 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch023 j hj hr]; exact walk_sound q _ 5888 h023 j _)
  have P25 := FKLBridge.Rows.range_step 6144 256 6400 rfl P24 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch024 j hj hr]; exact walk_sound q _ 6144 h024 j _)
  have P26 := FKLBridge.Rows.range_step 6400 256 6656 rfl P25 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch025 j hj hr]; exact walk_sound q _ 6400 h025 j _)
  have P27 := FKLBridge.Rows.range_step 6656 256 6912 rfl P26 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch026 j hj hr]; exact walk_sound q _ 6656 h026 j _)
  have P28 := FKLBridge.Rows.range_step 6912 256 7168 rfl P27 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch027 j hj hr]; exact walk_sound q _ 6912 h027 j _)
  have P29 := FKLBridge.Rows.range_step 7168 256 7424 rfl P28 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch028 j hj hr]; exact walk_sound q _ 7168 h028 j _)
  have P30 := FKLBridge.Rows.range_step 7424 256 7680 rfl P29 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch029 j hj hr]; exact walk_sound q _ 7424 h029 j _)
  have P31 := FKLBridge.Rows.range_step 7680 256 7936 rfl P30 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch030 j hj hr]; exact walk_sound q _ 7680 h030 j _)
  have P32 := FKLBridge.Rows.range_step 7936 256 8192 rfl P31 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch031 j hj hr]; exact walk_sound q _ 7936 h031 j _)
  have P33 := FKLBridge.Rows.range_step 8192 256 8448 rfl P32 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch032 j hj hr]; exact walk_sound q _ 8192 h032 j _)
  have P34 := FKLBridge.Rows.range_step 8448 256 8704 rfl P33 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch033 j hj hr]; exact walk_sound q _ 8448 h033 j _)
  have P35 := FKLBridge.Rows.range_step 8704 256 8960 rfl P34 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch034 j hj hr]; exact walk_sound q _ 8704 h034 j _)
  have P36 := FKLBridge.Rows.range_step 8960 256 9216 rfl P35 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch035 j hj hr]; exact walk_sound q _ 8960 h035 j _)
  have P37 := FKLBridge.Rows.range_step 9216 256 9472 rfl P36 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch036 j hj hr]; exact walk_sound q _ 9216 h036 j _)
  have P38 := FKLBridge.Rows.range_step 9472 256 9728 rfl P37 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch037 j hj hr]; exact walk_sound q _ 9472 h037 j _)
  have P39 := FKLBridge.Rows.range_step 9728 256 9984 rfl P38 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch038 j hj hr]; exact walk_sound q _ 9728 h038 j _)
  have P40 := FKLBridge.Rows.range_step 9984 256 10240 rfl P39 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch039 j hj hr]; exact walk_sound q _ 9984 h039 j _)
  have P41 := FKLBridge.Rows.range_step 10240 256 10496 rfl P40 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch040 j hj hr]; exact walk_sound q _ 10240 h040 j _)
  have P42 := FKLBridge.Rows.range_step 10496 256 10752 rfl P41 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch041 j hj hr]; exact walk_sound q _ 10496 h041 j _)
  have P43 := FKLBridge.Rows.range_step 10752 256 11008 rfl P42 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch042 j hj hr]; exact walk_sound q _ 10752 h042 j _)
  have P44 := FKLBridge.Rows.range_step 11008 256 11264 rfl P43 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch043 j hj hr]; exact walk_sound q _ 11008 h043 j _)
  have P45 := FKLBridge.Rows.range_step 11264 256 11520 rfl P44 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch044 j hj hr]; exact walk_sound q _ 11264 h044 j _)
  have P46 := FKLBridge.Rows.range_step 11520 256 11776 rfl P45 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch045 j hj hr]; exact walk_sound q _ 11520 h045 j _)
  have P47 := FKLBridge.Rows.range_step 11776 256 12032 rfl P46 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch046 j hj hr]; exact walk_sound q _ 11776 h046 j _)
  have P48 := FKLBridge.Rows.range_step 12032 256 12288 rfl P47 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch047 j hj hr]; exact walk_sound q _ 12032 h047 j _)
  have P49 := FKLBridge.Rows.range_step 12288 256 12544 rfl P48 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch048 j hj hr]; exact walk_sound q _ 12288 h048 j _)
  have P50 := FKLBridge.Rows.range_step 12544 256 12800 rfl P49 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch049 j hj hr]; exact walk_sound q _ 12544 h049 j _)
  have P51 := FKLBridge.Rows.range_step 12800 256 13056 rfl P50 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch050 j hj hr]; exact walk_sound q _ 12800 h050 j _)
  have P52 := FKLBridge.Rows.range_step 13056 256 13312 rfl P51 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch051 j hj hr]; exact walk_sound q _ 13056 h051 j _)
  have P53 := FKLBridge.Rows.range_step 13312 256 13568 rfl P52 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch052 j hj hr]; exact walk_sound q _ 13312 h052 j _)
  have P54 := FKLBridge.Rows.range_step 13568 256 13824 rfl P53 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch053 j hj hr]; exact walk_sound q _ 13568 h053 j _)
  have P55 := FKLBridge.Rows.range_step 13824 256 14080 rfl P54 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch054 j hj hr]; exact walk_sound q _ 13824 h054 j _)
  have P56 := FKLBridge.Rows.range_step 14080 256 14336 rfl P55 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch055 j hj hr]; exact walk_sound q _ 14080 h055 j _)
  have P57 := FKLBridge.Rows.range_step 14336 256 14592 rfl P56 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch056 j hj hr]; exact walk_sound q _ 14336 h056 j _)
  have P58 := FKLBridge.Rows.range_step 14592 256 14848 rfl P57 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch057 j hj hr]; exact walk_sound q _ 14592 h057 j _)
  have P59 := FKLBridge.Rows.range_step 14848 256 15104 rfl P58 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch058 j hj hr]; exact walk_sound q _ 14848 h058 j _)
  have P60 := FKLBridge.Rows.range_step 15104 175 15279 rfl P59 (fun j hj hr => by
    rw [FKLBridge.Dyadic.dispatch059 j hj hr]; exact walk_sound q _ 15104 h059 j _)
  intro r
  exact P60 r.val r.isLt r.isLt

end FKLMeta.DyWalk
