module

public import FKLMeta.Walk
public import FKLBridge.Gibbs

/-! Every row of `IndexedCertificateRows.gibbs` satisfies a raw test `q`, checked by one walk over the
literal parts `GibbsCertificateData.Part###.rows`. Generated by `gen_walks.py`. -/

@[expose] public section

namespace FKLMeta.GiWalk

open MatrixBounds.Numeric
set_option maxRecDepth 100000

/-- Walk all 130 literal parts. -/
def allRows (q : Nat → GibbsRow → Bool) : Bool :=
  Bool.and (walk q GibbsCertificateData.Part000.rows 0)
    (Bool.and (walk q GibbsCertificateData.Part001.rows 128)
    (Bool.and (walk q GibbsCertificateData.Part002.rows 256)
    (Bool.and (walk q GibbsCertificateData.Part003.rows 384)
    (Bool.and (walk q GibbsCertificateData.Part004.rows 512)
    (Bool.and (walk q GibbsCertificateData.Part005.rows 640)
    (Bool.and (walk q GibbsCertificateData.Part006.rows 768)
    (Bool.and (walk q GibbsCertificateData.Part007.rows 896)
    (Bool.and (walk q GibbsCertificateData.Part008.rows 1024)
    (Bool.and (walk q GibbsCertificateData.Part009.rows 1152)
    (Bool.and (walk q GibbsCertificateData.Part010.rows 1280)
    (Bool.and (walk q GibbsCertificateData.Part011.rows 1408)
    (Bool.and (walk q GibbsCertificateData.Part012.rows 1536)
    (Bool.and (walk q GibbsCertificateData.Part013.rows 1664)
    (Bool.and (walk q GibbsCertificateData.Part014.rows 1792)
    (Bool.and (walk q GibbsCertificateData.Part015.rows 1920)
    (Bool.and (walk q GibbsCertificateData.Part016.rows 2048)
    (Bool.and (walk q GibbsCertificateData.Part017.rows 2176)
    (Bool.and (walk q GibbsCertificateData.Part018.rows 2304)
    (Bool.and (walk q GibbsCertificateData.Part019.rows 2432)
    (Bool.and (walk q GibbsCertificateData.Part020.rows 2560)
    (Bool.and (walk q GibbsCertificateData.Part021.rows 2688)
    (Bool.and (walk q GibbsCertificateData.Part022.rows 2816)
    (Bool.and (walk q GibbsCertificateData.Part023.rows 2944)
    (Bool.and (walk q GibbsCertificateData.Part024.rows 3072)
    (Bool.and (walk q GibbsCertificateData.Part025.rows 3200)
    (Bool.and (walk q GibbsCertificateData.Part026.rows 3328)
    (Bool.and (walk q GibbsCertificateData.Part027.rows 3456)
    (Bool.and (walk q GibbsCertificateData.Part028.rows 3584)
    (Bool.and (walk q GibbsCertificateData.Part029.rows 3712)
    (Bool.and (walk q GibbsCertificateData.Part030.rows 3840)
    (Bool.and (walk q GibbsCertificateData.Part031.rows 3968)
    (Bool.and (walk q GibbsCertificateData.Part032.rows 4096)
    (Bool.and (walk q GibbsCertificateData.Part033.rows 4224)
    (Bool.and (walk q GibbsCertificateData.Part034.rows 4352)
    (Bool.and (walk q GibbsCertificateData.Part035.rows 4480)
    (Bool.and (walk q GibbsCertificateData.Part036.rows 4608)
    (Bool.and (walk q GibbsCertificateData.Part037.rows 4736)
    (Bool.and (walk q GibbsCertificateData.Part038.rows 4864)
    (Bool.and (walk q GibbsCertificateData.Part039.rows 4992)
    (Bool.and (walk q GibbsCertificateData.Part040.rows 5120)
    (Bool.and (walk q GibbsCertificateData.Part041.rows 5248)
    (Bool.and (walk q GibbsCertificateData.Part042.rows 5376)
    (Bool.and (walk q GibbsCertificateData.Part043.rows 5504)
    (Bool.and (walk q GibbsCertificateData.Part044.rows 5632)
    (Bool.and (walk q GibbsCertificateData.Part045.rows 5760)
    (Bool.and (walk q GibbsCertificateData.Part046.rows 5888)
    (Bool.and (walk q GibbsCertificateData.Part047.rows 6016)
    (Bool.and (walk q GibbsCertificateData.Part048.rows 6144)
    (Bool.and (walk q GibbsCertificateData.Part049.rows 6272)
    (Bool.and (walk q GibbsCertificateData.Part050.rows 6400)
    (Bool.and (walk q GibbsCertificateData.Part051.rows 6528)
    (Bool.and (walk q GibbsCertificateData.Part052.rows 6656)
    (Bool.and (walk q GibbsCertificateData.Part053.rows 6784)
    (Bool.and (walk q GibbsCertificateData.Part054.rows 6912)
    (Bool.and (walk q GibbsCertificateData.Part055.rows 7040)
    (Bool.and (walk q GibbsCertificateData.Part056.rows 7168)
    (Bool.and (walk q GibbsCertificateData.Part057.rows 7296)
    (Bool.and (walk q GibbsCertificateData.Part058.rows 7424)
    (Bool.and (walk q GibbsCertificateData.Part059.rows 7552)
    (Bool.and (walk q GibbsCertificateData.Part060.rows 7680)
    (Bool.and (walk q GibbsCertificateData.Part061.rows 7808)
    (Bool.and (walk q GibbsCertificateData.Part062.rows 7936)
    (Bool.and (walk q GibbsCertificateData.Part063.rows 8064)
    (Bool.and (walk q GibbsCertificateData.Part064.rows 8192)
    (Bool.and (walk q GibbsCertificateData.Part065.rows 8320)
    (Bool.and (walk q GibbsCertificateData.Part066.rows 8448)
    (Bool.and (walk q GibbsCertificateData.Part067.rows 8576)
    (Bool.and (walk q GibbsCertificateData.Part068.rows 8704)
    (Bool.and (walk q GibbsCertificateData.Part069.rows 8832)
    (Bool.and (walk q GibbsCertificateData.Part070.rows 8960)
    (Bool.and (walk q GibbsCertificateData.Part071.rows 9088)
    (Bool.and (walk q GibbsCertificateData.Part072.rows 9216)
    (Bool.and (walk q GibbsCertificateData.Part073.rows 9344)
    (Bool.and (walk q GibbsCertificateData.Part074.rows 9472)
    (Bool.and (walk q GibbsCertificateData.Part075.rows 9600)
    (Bool.and (walk q GibbsCertificateData.Part076.rows 9728)
    (Bool.and (walk q GibbsCertificateData.Part077.rows 9856)
    (Bool.and (walk q GibbsCertificateData.Part078.rows 9984)
    (Bool.and (walk q GibbsCertificateData.Part079.rows 10112)
    (Bool.and (walk q GibbsCertificateData.Part080.rows 10240)
    (Bool.and (walk q GibbsCertificateData.Part081.rows 10368)
    (Bool.and (walk q GibbsCertificateData.Part082.rows 10496)
    (Bool.and (walk q GibbsCertificateData.Part083.rows 10624)
    (Bool.and (walk q GibbsCertificateData.Part084.rows 10752)
    (Bool.and (walk q GibbsCertificateData.Part085.rows 10880)
    (Bool.and (walk q GibbsCertificateData.Part086.rows 11008)
    (Bool.and (walk q GibbsCertificateData.Part087.rows 11136)
    (Bool.and (walk q GibbsCertificateData.Part088.rows 11264)
    (Bool.and (walk q GibbsCertificateData.Part089.rows 11392)
    (Bool.and (walk q GibbsCertificateData.Part090.rows 11520)
    (Bool.and (walk q GibbsCertificateData.Part091.rows 11648)
    (Bool.and (walk q GibbsCertificateData.Part092.rows 11776)
    (Bool.and (walk q GibbsCertificateData.Part093.rows 11904)
    (Bool.and (walk q GibbsCertificateData.Part094.rows 12032)
    (Bool.and (walk q GibbsCertificateData.Part095.rows 12160)
    (Bool.and (walk q GibbsCertificateData.Part096.rows 12288)
    (Bool.and (walk q GibbsCertificateData.Part097.rows 12416)
    (Bool.and (walk q GibbsCertificateData.Part098.rows 12544)
    (Bool.and (walk q GibbsCertificateData.Part099.rows 12672)
    (Bool.and (walk q GibbsCertificateData.Part100.rows 12800)
    (Bool.and (walk q GibbsCertificateData.Part101.rows 12928)
    (Bool.and (walk q GibbsCertificateData.Part102.rows 13056)
    (Bool.and (walk q GibbsCertificateData.Part103.rows 13184)
    (Bool.and (walk q GibbsCertificateData.Part104.rows 13312)
    (Bool.and (walk q GibbsCertificateData.Part105.rows 13440)
    (Bool.and (walk q GibbsCertificateData.Part106.rows 13568)
    (Bool.and (walk q GibbsCertificateData.Part107.rows 13696)
    (Bool.and (walk q GibbsCertificateData.Part108.rows 13824)
    (Bool.and (walk q GibbsCertificateData.Part109.rows 13952)
    (Bool.and (walk q GibbsCertificateData.Part110.rows 14080)
    (Bool.and (walk q GibbsCertificateData.Part111.rows 14208)
    (Bool.and (walk q GibbsCertificateData.Part112.rows 14336)
    (Bool.and (walk q GibbsCertificateData.Part113.rows 14464)
    (Bool.and (walk q GibbsCertificateData.Part114.rows 14592)
    (Bool.and (walk q GibbsCertificateData.Part115.rows 14720)
    (Bool.and (walk q GibbsCertificateData.Part116.rows 14848)
    (Bool.and (walk q GibbsCertificateData.Part117.rows 14976)
    (Bool.and (walk q GibbsCertificateData.Part118.rows 15104)
    (Bool.and (walk q GibbsCertificateData.Part119.rows 15232)
    (Bool.and (walk q GibbsCertificateData.Part120.rows 15360)
    (Bool.and (walk q GibbsCertificateData.Part121.rows 15488)
    (Bool.and (walk q GibbsCertificateData.Part122.rows 15616)
    (Bool.and (walk q GibbsCertificateData.Part123.rows 15744)
    (Bool.and (walk q GibbsCertificateData.Part124.rows 15872)
    (Bool.and (walk q GibbsCertificateData.Part125.rows 16000)
    (Bool.and (walk q GibbsCertificateData.Part126.rows 16128)
    (Bool.and (walk q GibbsCertificateData.Part127.rows 16256)
    (Bool.and (walk q GibbsCertificateData.Part128.rows 16384)
    (walk q GibbsCertificateData.Part129.rows 16512)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem allRows_sound (q : Nat → GibbsRow → Bool) (h : allRows q = true) :
    ∀ r : Fin 16629, q r.val (IndexedCertificateRows.gibbs r).val = true := by
  simp only [allRows, Bool.and_eq_true] at h
  obtain ⟨h000, h001, h002, h003, h004, h005, h006, h007, h008, h009, h010, h011, h012, h013, h014, h015, h016, h017, h018, h019, h020, h021, h022, h023, h024, h025, h026, h027, h028, h029, h030, h031, h032, h033, h034, h035, h036, h037, h038, h039, h040, h041, h042, h043, h044, h045, h046, h047, h048, h049, h050, h051, h052, h053, h054, h055, h056, h057, h058, h059, h060, h061, h062, h063, h064, h065, h066, h067, h068, h069, h070, h071, h072, h073, h074, h075, h076, h077, h078, h079, h080, h081, h082, h083, h084, h085, h086, h087, h088, h089, h090, h091, h092, h093, h094, h095, h096, h097, h098, h099, h100, h101, h102, h103, h104, h105, h106, h107, h108, h109, h110, h111, h112, h113, h114, h115, h116, h117, h118, h119, h120, h121, h122, h123, h124, h125, h126, h127, h128, h129⟩ := h
  have P0 : ∀ r < 0, ∀ hr : r < 16629, q r (IndexedCertificateRows.gibbs ⟨r, hr⟩).val = true :=
    FKLBridge.Rows.range_zero
  have P1 := FKLBridge.Rows.range_step 0 128 128 rfl P0 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch000 j hj hr]; exact walk_sound q _ 0 h000 j _)
  have P2 := FKLBridge.Rows.range_step 128 128 256 rfl P1 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch001 j hj hr]; exact walk_sound q _ 128 h001 j _)
  have P3 := FKLBridge.Rows.range_step 256 128 384 rfl P2 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch002 j hj hr]; exact walk_sound q _ 256 h002 j _)
  have P4 := FKLBridge.Rows.range_step 384 128 512 rfl P3 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch003 j hj hr]; exact walk_sound q _ 384 h003 j _)
  have P5 := FKLBridge.Rows.range_step 512 128 640 rfl P4 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch004 j hj hr]; exact walk_sound q _ 512 h004 j _)
  have P6 := FKLBridge.Rows.range_step 640 128 768 rfl P5 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch005 j hj hr]; exact walk_sound q _ 640 h005 j _)
  have P7 := FKLBridge.Rows.range_step 768 128 896 rfl P6 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch006 j hj hr]; exact walk_sound q _ 768 h006 j _)
  have P8 := FKLBridge.Rows.range_step 896 128 1024 rfl P7 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch007 j hj hr]; exact walk_sound q _ 896 h007 j _)
  have P9 := FKLBridge.Rows.range_step 1024 128 1152 rfl P8 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch008 j hj hr]; exact walk_sound q _ 1024 h008 j _)
  have P10 := FKLBridge.Rows.range_step 1152 128 1280 rfl P9 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch009 j hj hr]; exact walk_sound q _ 1152 h009 j _)
  have P11 := FKLBridge.Rows.range_step 1280 128 1408 rfl P10 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch010 j hj hr]; exact walk_sound q _ 1280 h010 j _)
  have P12 := FKLBridge.Rows.range_step 1408 128 1536 rfl P11 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch011 j hj hr]; exact walk_sound q _ 1408 h011 j _)
  have P13 := FKLBridge.Rows.range_step 1536 128 1664 rfl P12 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch012 j hj hr]; exact walk_sound q _ 1536 h012 j _)
  have P14 := FKLBridge.Rows.range_step 1664 128 1792 rfl P13 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch013 j hj hr]; exact walk_sound q _ 1664 h013 j _)
  have P15 := FKLBridge.Rows.range_step 1792 128 1920 rfl P14 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch014 j hj hr]; exact walk_sound q _ 1792 h014 j _)
  have P16 := FKLBridge.Rows.range_step 1920 128 2048 rfl P15 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch015 j hj hr]; exact walk_sound q _ 1920 h015 j _)
  have P17 := FKLBridge.Rows.range_step 2048 128 2176 rfl P16 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch016 j hj hr]; exact walk_sound q _ 2048 h016 j _)
  have P18 := FKLBridge.Rows.range_step 2176 128 2304 rfl P17 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch017 j hj hr]; exact walk_sound q _ 2176 h017 j _)
  have P19 := FKLBridge.Rows.range_step 2304 128 2432 rfl P18 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch018 j hj hr]; exact walk_sound q _ 2304 h018 j _)
  have P20 := FKLBridge.Rows.range_step 2432 128 2560 rfl P19 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch019 j hj hr]; exact walk_sound q _ 2432 h019 j _)
  have P21 := FKLBridge.Rows.range_step 2560 128 2688 rfl P20 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch020 j hj hr]; exact walk_sound q _ 2560 h020 j _)
  have P22 := FKLBridge.Rows.range_step 2688 128 2816 rfl P21 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch021 j hj hr]; exact walk_sound q _ 2688 h021 j _)
  have P23 := FKLBridge.Rows.range_step 2816 128 2944 rfl P22 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch022 j hj hr]; exact walk_sound q _ 2816 h022 j _)
  have P24 := FKLBridge.Rows.range_step 2944 128 3072 rfl P23 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch023 j hj hr]; exact walk_sound q _ 2944 h023 j _)
  have P25 := FKLBridge.Rows.range_step 3072 128 3200 rfl P24 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch024 j hj hr]; exact walk_sound q _ 3072 h024 j _)
  have P26 := FKLBridge.Rows.range_step 3200 128 3328 rfl P25 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch025 j hj hr]; exact walk_sound q _ 3200 h025 j _)
  have P27 := FKLBridge.Rows.range_step 3328 128 3456 rfl P26 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch026 j hj hr]; exact walk_sound q _ 3328 h026 j _)
  have P28 := FKLBridge.Rows.range_step 3456 128 3584 rfl P27 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch027 j hj hr]; exact walk_sound q _ 3456 h027 j _)
  have P29 := FKLBridge.Rows.range_step 3584 128 3712 rfl P28 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch028 j hj hr]; exact walk_sound q _ 3584 h028 j _)
  have P30 := FKLBridge.Rows.range_step 3712 128 3840 rfl P29 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch029 j hj hr]; exact walk_sound q _ 3712 h029 j _)
  have P31 := FKLBridge.Rows.range_step 3840 128 3968 rfl P30 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch030 j hj hr]; exact walk_sound q _ 3840 h030 j _)
  have P32 := FKLBridge.Rows.range_step 3968 128 4096 rfl P31 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch031 j hj hr]; exact walk_sound q _ 3968 h031 j _)
  have P33 := FKLBridge.Rows.range_step 4096 128 4224 rfl P32 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch032 j hj hr]; exact walk_sound q _ 4096 h032 j _)
  have P34 := FKLBridge.Rows.range_step 4224 128 4352 rfl P33 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch033 j hj hr]; exact walk_sound q _ 4224 h033 j _)
  have P35 := FKLBridge.Rows.range_step 4352 128 4480 rfl P34 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch034 j hj hr]; exact walk_sound q _ 4352 h034 j _)
  have P36 := FKLBridge.Rows.range_step 4480 128 4608 rfl P35 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch035 j hj hr]; exact walk_sound q _ 4480 h035 j _)
  have P37 := FKLBridge.Rows.range_step 4608 128 4736 rfl P36 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch036 j hj hr]; exact walk_sound q _ 4608 h036 j _)
  have P38 := FKLBridge.Rows.range_step 4736 128 4864 rfl P37 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch037 j hj hr]; exact walk_sound q _ 4736 h037 j _)
  have P39 := FKLBridge.Rows.range_step 4864 128 4992 rfl P38 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch038 j hj hr]; exact walk_sound q _ 4864 h038 j _)
  have P40 := FKLBridge.Rows.range_step 4992 128 5120 rfl P39 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch039 j hj hr]; exact walk_sound q _ 4992 h039 j _)
  have P41 := FKLBridge.Rows.range_step 5120 128 5248 rfl P40 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch040 j hj hr]; exact walk_sound q _ 5120 h040 j _)
  have P42 := FKLBridge.Rows.range_step 5248 128 5376 rfl P41 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch041 j hj hr]; exact walk_sound q _ 5248 h041 j _)
  have P43 := FKLBridge.Rows.range_step 5376 128 5504 rfl P42 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch042 j hj hr]; exact walk_sound q _ 5376 h042 j _)
  have P44 := FKLBridge.Rows.range_step 5504 128 5632 rfl P43 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch043 j hj hr]; exact walk_sound q _ 5504 h043 j _)
  have P45 := FKLBridge.Rows.range_step 5632 128 5760 rfl P44 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch044 j hj hr]; exact walk_sound q _ 5632 h044 j _)
  have P46 := FKLBridge.Rows.range_step 5760 128 5888 rfl P45 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch045 j hj hr]; exact walk_sound q _ 5760 h045 j _)
  have P47 := FKLBridge.Rows.range_step 5888 128 6016 rfl P46 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch046 j hj hr]; exact walk_sound q _ 5888 h046 j _)
  have P48 := FKLBridge.Rows.range_step 6016 128 6144 rfl P47 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch047 j hj hr]; exact walk_sound q _ 6016 h047 j _)
  have P49 := FKLBridge.Rows.range_step 6144 128 6272 rfl P48 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch048 j hj hr]; exact walk_sound q _ 6144 h048 j _)
  have P50 := FKLBridge.Rows.range_step 6272 128 6400 rfl P49 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch049 j hj hr]; exact walk_sound q _ 6272 h049 j _)
  have P51 := FKLBridge.Rows.range_step 6400 128 6528 rfl P50 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch050 j hj hr]; exact walk_sound q _ 6400 h050 j _)
  have P52 := FKLBridge.Rows.range_step 6528 128 6656 rfl P51 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch051 j hj hr]; exact walk_sound q _ 6528 h051 j _)
  have P53 := FKLBridge.Rows.range_step 6656 128 6784 rfl P52 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch052 j hj hr]; exact walk_sound q _ 6656 h052 j _)
  have P54 := FKLBridge.Rows.range_step 6784 128 6912 rfl P53 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch053 j hj hr]; exact walk_sound q _ 6784 h053 j _)
  have P55 := FKLBridge.Rows.range_step 6912 128 7040 rfl P54 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch054 j hj hr]; exact walk_sound q _ 6912 h054 j _)
  have P56 := FKLBridge.Rows.range_step 7040 128 7168 rfl P55 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch055 j hj hr]; exact walk_sound q _ 7040 h055 j _)
  have P57 := FKLBridge.Rows.range_step 7168 128 7296 rfl P56 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch056 j hj hr]; exact walk_sound q _ 7168 h056 j _)
  have P58 := FKLBridge.Rows.range_step 7296 128 7424 rfl P57 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch057 j hj hr]; exact walk_sound q _ 7296 h057 j _)
  have P59 := FKLBridge.Rows.range_step 7424 128 7552 rfl P58 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch058 j hj hr]; exact walk_sound q _ 7424 h058 j _)
  have P60 := FKLBridge.Rows.range_step 7552 128 7680 rfl P59 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch059 j hj hr]; exact walk_sound q _ 7552 h059 j _)
  have P61 := FKLBridge.Rows.range_step 7680 128 7808 rfl P60 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch060 j hj hr]; exact walk_sound q _ 7680 h060 j _)
  have P62 := FKLBridge.Rows.range_step 7808 128 7936 rfl P61 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch061 j hj hr]; exact walk_sound q _ 7808 h061 j _)
  have P63 := FKLBridge.Rows.range_step 7936 128 8064 rfl P62 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch062 j hj hr]; exact walk_sound q _ 7936 h062 j _)
  have P64 := FKLBridge.Rows.range_step 8064 128 8192 rfl P63 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch063 j hj hr]; exact walk_sound q _ 8064 h063 j _)
  have P65 := FKLBridge.Rows.range_step 8192 128 8320 rfl P64 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch064 j hj hr]; exact walk_sound q _ 8192 h064 j _)
  have P66 := FKLBridge.Rows.range_step 8320 128 8448 rfl P65 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch065 j hj hr]; exact walk_sound q _ 8320 h065 j _)
  have P67 := FKLBridge.Rows.range_step 8448 128 8576 rfl P66 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch066 j hj hr]; exact walk_sound q _ 8448 h066 j _)
  have P68 := FKLBridge.Rows.range_step 8576 128 8704 rfl P67 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch067 j hj hr]; exact walk_sound q _ 8576 h067 j _)
  have P69 := FKLBridge.Rows.range_step 8704 128 8832 rfl P68 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch068 j hj hr]; exact walk_sound q _ 8704 h068 j _)
  have P70 := FKLBridge.Rows.range_step 8832 128 8960 rfl P69 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch069 j hj hr]; exact walk_sound q _ 8832 h069 j _)
  have P71 := FKLBridge.Rows.range_step 8960 128 9088 rfl P70 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch070 j hj hr]; exact walk_sound q _ 8960 h070 j _)
  have P72 := FKLBridge.Rows.range_step 9088 128 9216 rfl P71 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch071 j hj hr]; exact walk_sound q _ 9088 h071 j _)
  have P73 := FKLBridge.Rows.range_step 9216 128 9344 rfl P72 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch072 j hj hr]; exact walk_sound q _ 9216 h072 j _)
  have P74 := FKLBridge.Rows.range_step 9344 128 9472 rfl P73 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch073 j hj hr]; exact walk_sound q _ 9344 h073 j _)
  have P75 := FKLBridge.Rows.range_step 9472 128 9600 rfl P74 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch074 j hj hr]; exact walk_sound q _ 9472 h074 j _)
  have P76 := FKLBridge.Rows.range_step 9600 128 9728 rfl P75 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch075 j hj hr]; exact walk_sound q _ 9600 h075 j _)
  have P77 := FKLBridge.Rows.range_step 9728 128 9856 rfl P76 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch076 j hj hr]; exact walk_sound q _ 9728 h076 j _)
  have P78 := FKLBridge.Rows.range_step 9856 128 9984 rfl P77 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch077 j hj hr]; exact walk_sound q _ 9856 h077 j _)
  have P79 := FKLBridge.Rows.range_step 9984 128 10112 rfl P78 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch078 j hj hr]; exact walk_sound q _ 9984 h078 j _)
  have P80 := FKLBridge.Rows.range_step 10112 128 10240 rfl P79 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch079 j hj hr]; exact walk_sound q _ 10112 h079 j _)
  have P81 := FKLBridge.Rows.range_step 10240 128 10368 rfl P80 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch080 j hj hr]; exact walk_sound q _ 10240 h080 j _)
  have P82 := FKLBridge.Rows.range_step 10368 128 10496 rfl P81 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch081 j hj hr]; exact walk_sound q _ 10368 h081 j _)
  have P83 := FKLBridge.Rows.range_step 10496 128 10624 rfl P82 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch082 j hj hr]; exact walk_sound q _ 10496 h082 j _)
  have P84 := FKLBridge.Rows.range_step 10624 128 10752 rfl P83 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch083 j hj hr]; exact walk_sound q _ 10624 h083 j _)
  have P85 := FKLBridge.Rows.range_step 10752 128 10880 rfl P84 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch084 j hj hr]; exact walk_sound q _ 10752 h084 j _)
  have P86 := FKLBridge.Rows.range_step 10880 128 11008 rfl P85 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch085 j hj hr]; exact walk_sound q _ 10880 h085 j _)
  have P87 := FKLBridge.Rows.range_step 11008 128 11136 rfl P86 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch086 j hj hr]; exact walk_sound q _ 11008 h086 j _)
  have P88 := FKLBridge.Rows.range_step 11136 128 11264 rfl P87 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch087 j hj hr]; exact walk_sound q _ 11136 h087 j _)
  have P89 := FKLBridge.Rows.range_step 11264 128 11392 rfl P88 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch088 j hj hr]; exact walk_sound q _ 11264 h088 j _)
  have P90 := FKLBridge.Rows.range_step 11392 128 11520 rfl P89 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch089 j hj hr]; exact walk_sound q _ 11392 h089 j _)
  have P91 := FKLBridge.Rows.range_step 11520 128 11648 rfl P90 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch090 j hj hr]; exact walk_sound q _ 11520 h090 j _)
  have P92 := FKLBridge.Rows.range_step 11648 128 11776 rfl P91 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch091 j hj hr]; exact walk_sound q _ 11648 h091 j _)
  have P93 := FKLBridge.Rows.range_step 11776 128 11904 rfl P92 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch092 j hj hr]; exact walk_sound q _ 11776 h092 j _)
  have P94 := FKLBridge.Rows.range_step 11904 128 12032 rfl P93 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch093 j hj hr]; exact walk_sound q _ 11904 h093 j _)
  have P95 := FKLBridge.Rows.range_step 12032 128 12160 rfl P94 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch094 j hj hr]; exact walk_sound q _ 12032 h094 j _)
  have P96 := FKLBridge.Rows.range_step 12160 128 12288 rfl P95 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch095 j hj hr]; exact walk_sound q _ 12160 h095 j _)
  have P97 := FKLBridge.Rows.range_step 12288 128 12416 rfl P96 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch096 j hj hr]; exact walk_sound q _ 12288 h096 j _)
  have P98 := FKLBridge.Rows.range_step 12416 128 12544 rfl P97 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch097 j hj hr]; exact walk_sound q _ 12416 h097 j _)
  have P99 := FKLBridge.Rows.range_step 12544 128 12672 rfl P98 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch098 j hj hr]; exact walk_sound q _ 12544 h098 j _)
  have P100 := FKLBridge.Rows.range_step 12672 128 12800 rfl P99 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch099 j hj hr]; exact walk_sound q _ 12672 h099 j _)
  have P101 := FKLBridge.Rows.range_step 12800 128 12928 rfl P100 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch100 j hj hr]; exact walk_sound q _ 12800 h100 j _)
  have P102 := FKLBridge.Rows.range_step 12928 128 13056 rfl P101 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch101 j hj hr]; exact walk_sound q _ 12928 h101 j _)
  have P103 := FKLBridge.Rows.range_step 13056 128 13184 rfl P102 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch102 j hj hr]; exact walk_sound q _ 13056 h102 j _)
  have P104 := FKLBridge.Rows.range_step 13184 128 13312 rfl P103 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch103 j hj hr]; exact walk_sound q _ 13184 h103 j _)
  have P105 := FKLBridge.Rows.range_step 13312 128 13440 rfl P104 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch104 j hj hr]; exact walk_sound q _ 13312 h104 j _)
  have P106 := FKLBridge.Rows.range_step 13440 128 13568 rfl P105 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch105 j hj hr]; exact walk_sound q _ 13440 h105 j _)
  have P107 := FKLBridge.Rows.range_step 13568 128 13696 rfl P106 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch106 j hj hr]; exact walk_sound q _ 13568 h106 j _)
  have P108 := FKLBridge.Rows.range_step 13696 128 13824 rfl P107 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch107 j hj hr]; exact walk_sound q _ 13696 h107 j _)
  have P109 := FKLBridge.Rows.range_step 13824 128 13952 rfl P108 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch108 j hj hr]; exact walk_sound q _ 13824 h108 j _)
  have P110 := FKLBridge.Rows.range_step 13952 128 14080 rfl P109 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch109 j hj hr]; exact walk_sound q _ 13952 h109 j _)
  have P111 := FKLBridge.Rows.range_step 14080 128 14208 rfl P110 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch110 j hj hr]; exact walk_sound q _ 14080 h110 j _)
  have P112 := FKLBridge.Rows.range_step 14208 128 14336 rfl P111 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch111 j hj hr]; exact walk_sound q _ 14208 h111 j _)
  have P113 := FKLBridge.Rows.range_step 14336 128 14464 rfl P112 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch112 j hj hr]; exact walk_sound q _ 14336 h112 j _)
  have P114 := FKLBridge.Rows.range_step 14464 128 14592 rfl P113 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch113 j hj hr]; exact walk_sound q _ 14464 h113 j _)
  have P115 := FKLBridge.Rows.range_step 14592 128 14720 rfl P114 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch114 j hj hr]; exact walk_sound q _ 14592 h114 j _)
  have P116 := FKLBridge.Rows.range_step 14720 128 14848 rfl P115 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch115 j hj hr]; exact walk_sound q _ 14720 h115 j _)
  have P117 := FKLBridge.Rows.range_step 14848 128 14976 rfl P116 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch116 j hj hr]; exact walk_sound q _ 14848 h116 j _)
  have P118 := FKLBridge.Rows.range_step 14976 128 15104 rfl P117 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch117 j hj hr]; exact walk_sound q _ 14976 h117 j _)
  have P119 := FKLBridge.Rows.range_step 15104 128 15232 rfl P118 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch118 j hj hr]; exact walk_sound q _ 15104 h118 j _)
  have P120 := FKLBridge.Rows.range_step 15232 128 15360 rfl P119 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch119 j hj hr]; exact walk_sound q _ 15232 h119 j _)
  have P121 := FKLBridge.Rows.range_step 15360 128 15488 rfl P120 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch120 j hj hr]; exact walk_sound q _ 15360 h120 j _)
  have P122 := FKLBridge.Rows.range_step 15488 128 15616 rfl P121 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch121 j hj hr]; exact walk_sound q _ 15488 h121 j _)
  have P123 := FKLBridge.Rows.range_step 15616 128 15744 rfl P122 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch122 j hj hr]; exact walk_sound q _ 15616 h122 j _)
  have P124 := FKLBridge.Rows.range_step 15744 128 15872 rfl P123 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch123 j hj hr]; exact walk_sound q _ 15744 h123 j _)
  have P125 := FKLBridge.Rows.range_step 15872 128 16000 rfl P124 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch124 j hj hr]; exact walk_sound q _ 15872 h124 j _)
  have P126 := FKLBridge.Rows.range_step 16000 128 16128 rfl P125 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch125 j hj hr]; exact walk_sound q _ 16000 h125 j _)
  have P127 := FKLBridge.Rows.range_step 16128 128 16256 rfl P126 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch126 j hj hr]; exact walk_sound q _ 16128 h126 j _)
  have P128 := FKLBridge.Rows.range_step 16256 128 16384 rfl P127 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch127 j hj hr]; exact walk_sound q _ 16256 h127 j _)
  have P129 := FKLBridge.Rows.range_step 16384 128 16512 rfl P128 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch128 j hj hr]; exact walk_sound q _ 16384 h128 j _)
  have P130 := FKLBridge.Rows.range_step 16512 117 16629 rfl P129 (fun j hj hr => by
    rw [FKLBridge.Gibbs.dispatch129 j hj hr]; exact walk_sound q _ 16512 h129 j _)
  intro r
  exact P130 r.val r.isLt r.isLt

end FKLMeta.GiWalk
