module

public import FKLMeta.Walk
public import FKL.Lane
public import SuppliedShapeIndices

/-! Packed copies of the shape enumerations `shapes 4/8/16`, the hierarchy node arrays and the child-column
lists of `SuppliedShapeIndices`, each linked to the original by one walk. Generated by `gen_nodes.py`. -/

@[expose] public section

namespace FKLMeta.Nodes

open MatrixBounds.Numeric SuppliedShapeIndices
set_option maxRecDepth 100000

def sx4 : ℕ := 0x1063108410842000000
def sy4 : ℕ := 0x20104031040418820
def sz4 : ℕ := 0x1004400886008864

theorem shapes4_checked : FKLMeta.walk (fun c s => Bool.and (Nat.beq s.x (FKL.lane sx4 5 c))
    (Bool.and (Nat.beq s.y (FKL.lane sy4 5 c)) (Nat.beq s.z (FKL.lane sz4 5 c)))) (shapes 4) 0 = true := by
  decide +kernel

theorem shapes4_len : (shapes 4).length = 15 := by decide +kernel

theorem shapes4_get (c : ℕ) (hc : c < 15) :
    (shapes 4)[c]? = some ⟨FKL.lane sx4 5 c, FKL.lane sy4 5 c, FKL.lane sz4 5 c⟩ := by
  have hc' : c < (shapes 4).length := by rw [shapes4_len]; exact hc
  have e := FKLMeta.walk_sound _ _ 0 shapes4_checked c hc'
  simp only [Nat.zero_add, Bool.and_eq_true, Nat.beq_eq] at e
  rw [List.getElem?_eq_getElem hc', ← e.1, ← e.2.1, ← e.2.2]

theorem shapeAt4 (c : ℕ) (hc : c < 15) :
    shapeAt 4 c = ⟨FKL.lane sx4 5 c, FKL.lane sy4 5 c, FKL.lane sz4 5 c⟩ := by
  unfold shapeAt; rw [shapes4_get c hc]; rfl

def sx8 : ℕ := 0x839cc6314a5290842106318c63108421084108421084200000000000
def sy8 : ℕ := 0x804100c4101062080a41882031483104073148310408398a418820
def sz8 : ℕ := 0x40110022180221900110c8500443214c008864298e008864298e8

theorem shapes8_checked : FKLMeta.walk (fun c s => Bool.and (Nat.beq s.x (FKL.lane sx8 5 c))
    (Bool.and (Nat.beq s.y (FKL.lane sy8 5 c)) (Nat.beq s.z (FKL.lane sz8 5 c)))) (shapes 8) 0 = true := by
  decide +kernel

theorem shapes8_len : (shapes 8).length = 45 := by decide +kernel

theorem shapes8_get (c : ℕ) (hc : c < 45) :
    (shapes 8)[c]? = some ⟨FKL.lane sx8 5 c, FKL.lane sy8 5 c, FKL.lane sz8 5 c⟩ := by
  have hc' : c < (shapes 8).length := by rw [shapes8_len]; exact hc
  have e := FKLMeta.walk_sound _ _ 0 shapes8_checked c hc'
  simp only [Nat.zero_add, Bool.and_eq_true, Nat.beq_eq] at e
  rw [List.getElem?_eq_getElem hc', ← e.1, ← e.2.1, ← e.2.2]

theorem shapeAt8 (c : ℕ) (hc : c < 45) :
    shapeAt 8 c = ⟨FKL.lane sx8 5 c, FKL.lane sy8 5 c, FKL.lane sz8 5 c⟩ := by
  unfold shapeAt; rw [shapes8_get c hc]; rfl

def sx16 : ℕ := 0x107bdce735ad6b18c6316b5ad6b5294a529494a5294a528421084210839ce739ce739cc6318c6318c6314a5294a5294a52908421084210842106318c6318c6318c63108421084210842108410842108421084210842000000000000000000000
def sy16 : ℕ := 0x804100c4101062080a41882031483104073148310408398a4188204a0e6290620814941cc520c4102d4941cc520c410316a4a0e629062081ac5a928398a4188207358b52507314831040f7358b5250731483104107b9ac5a928398a418820
def sz16 : ℕ := 0x40110022180221900110c8500443214c008864298e008864298e800443214c74240110c8531d0950022190a63a12a58022190a63a12a5b00110c8531d0952d8d00443214c74254b635c008864298e84a96c6b9e008864298e84a96c6b9f0

theorem shapes16_checked : FKLMeta.walk (fun c s => Bool.and (Nat.beq s.x (FKL.lane sx16 5 c))
    (Bool.and (Nat.beq s.y (FKL.lane sy16 5 c)) (Nat.beq s.z (FKL.lane sz16 5 c)))) (shapes 16) 0 = true := by
  decide +kernel

theorem shapes16_len : (shapes 16).length = 153 := by decide +kernel

theorem shapes16_get (c : ℕ) (hc : c < 153) :
    (shapes 16)[c]? = some ⟨FKL.lane sx16 5 c, FKL.lane sy16 5 c, FKL.lane sz16 5 c⟩ := by
  have hc' : c < (shapes 16).length := by rw [shapes16_len]; exact hc
  have e := FKLMeta.walk_sound _ _ 0 shapes16_checked c hc'
  simp only [Nat.zero_add, Bool.and_eq_true, Nat.beq_eq] at e
  rw [List.getElem?_eq_getElem hc', ← e.1, ← e.2.1, ← e.2.2]

theorem shapeAt16 (c : ℕ) (hc : c < 153) :
    shapeAt 16 c = ⟨FKL.lane sx16 5 c, FKL.lane sy16 5 c, FKL.lane sz16 5 c⟩ := by
  unfold shapeAt; rw [shapes16_get c hc]; rfl

def positiveP : ℕ := 0x68cf9f366cb972e4c993263c78f162c58b0e1c3870e1c183060c182fdfbf7ef5ebd7af5dbb76eddbb76edcb972e5cb972e5cb76eddbb76eddbb56ad5ab566cd9b366cd8b162c58b162c58b15ebd7af5ebd7af5ebd7af5ab56ad5ab56ad5ab56ad56ad5ab56ad5ab56ad4a952a54a94e9d3a74e9d2a54a952a54a952a54a8d1a3468d1a3468d1a3468d1a142850a142850a142850a14284f9f3e7cf9f3e7cf9f3e7cf9f3a74e9d3a74e9d3a74e9b366cd9b3664c993264c972e5cb972e5cb972e5ca952a54a952a54a952a54a952a4c993264c993264c993264c993264c891224489122448912244891224488f1e3c78f1e3c78f1e3c78f1e3c68d1a3468d1a3468d1a2c58b162c5891224489121c3870e1c3870e1c3870a142850a142850a142850a14283060c183060c183060c183060c18306040810204081020408102040810204080fdfbf7efdfbf7efdfbf7efdfbf7efdfbe7cf9f3e7cf9f3e7cf9f3e7cf9ebd7af5ebd7af5ebd7af1e3c78f1e3b76eddbb74e9d3a74e9d3a74e9cb972e5cb972e5cb972e5cb970e1c3870e1c3870e1c3870e1c3870ddbb76eddbb76eddbb76eddbb76eddbb76cd9b366cd9b366cd9b366cd9b366cd9b356ad5ab56ad5ab56ad5ab56ad5ab568d1a3468d1a3468d1a3468d19b366cd9b366cd9b364c993264c58b162c183060c183060bd7af5ebd7af5ebd7af5eb972e5cb972e5cb972e5cb972e5ab56ad5ab56ad5ab56ad5ab56ad5ab162c58b162c58b162c58b162c58b162b56ad5ab56ad5ab56ad5ab56ad5ab54a952a54a952a54a952a54a952952a54a952a54a952a54a850a142850a14274e9d3a64c992a54a952a548912244891224488d1a3468d1a3468d1a3468912244891224489122448912142850a142850a142850a14285020408102040810204081020407cf9f3e7cf9f3e7cf9f3e7cf9e3c78f1e3c78f1e3c78f1d3a74e9d3a74e9d3870e1c3870d9b3668d193264c983060c18305cb972e5cb972e58b162c58b162c58b152a54a952a54a952a54a142850a142850a14284c993264c993264c9932448912244891224488912244891224481020408101e3c78f1c3868c182c58b142850a1224489122040810204070e1c3870e183060c183050a142850a102040810183060c1020404080
def positiveC : ℕ := 0x28a25a24a2586896482891fa2585ca2592181ba259207daa247d9a2585c5a896486071b5689648607db694a259207da653a247d94a89617163e896486071b5953a89648607dc6da5543689648607db69951332896481f6994d22e891f6522a89617163e896486071b5953cea2592181f71b69655438da2592181f71b6995544cd3289648607db69951348c2e896481f6994d22caa247d948aa2585c58fa2592181c6d654f3a89648607dc6da59550f38da2592181f71b69959551338d3289648607dc6da65551348d30ba2592181f6da6544d230b2a896481f6994d22caa247d948aa2585c58fa2592181c6d654f3a89648607dc6da59550f38da2592181f71b6995955133ce34ca2592181f71b69959551348e34c2e89648607dc6da65551348d30b2a89648607db69951348c2caa259207da65348b2a891f6522a585c58f96486071b5953ce9648607dc6da59550f38d9648607dc6da6565544cf38d32592181f71b69959551348f38d30b9648607dc6da6565544d238d30b2a592181f71b6995544d234c2ca9648607db69951348c2ca96481f6994d22ca91f6522a17163e181c6d654f3a181f71b6965543ce36181f71b6995955133ce34c8607dc6da6565544d23ce34c2e181f71b69959551348f38d30b2a181f71b69959551348e34c2ca8607dc6da65551348d30b2a181f6da6544d230b2a07da65348b29f65229c58f71b5953ce71b6965543ce35c6da6565544cf38d31c6da6565544d23ce34c2dc6da6565544d23ce34c2ca71b69959551348f38d30b29c6da6565544d238d30b29c6da65551348d30b29b69951348c2ca6994d22ca6522963d654f3965543ce3565544cf38d3165544d23ce34c2d65544d23ce34c2ca59551348f38d30b2965544d23ce34c2ca59551348e34c2ca5544d234c2ca51348c2ca4d22ca48a3cf38f38d3ce34c3ce34c2cf38d30b28f38d30b28f38d30b28f38d30b28e34c2ca34c2ca30b28b28a
def positiveL : ℕ := 0x14a4e92a4e349ca1493e938ba939460da4e507b2927ae938b9549ca30735349ca307b588a4e507b167a49eb35271728b49ca3073549252728c1ee6b1281d2728c1ed62d071527283d8b3983493d6605271728b49ca3073549292939460f7358a4a083a4e5183dcd62d2838c549ca307b58b41cc20d27283d8b39820a49eb302938b945a4e51839aa494949ca307b9ac5250520e939460f7358b5250720c549ca307b9ac5a50730c41a4e5183dac5a0e6104149ca0f62ce6082927acc0a4e2e516939460e6a925252728c1ee6b14941483a4e5183dcd62d4941ca418a939460f7358b52507310620d2728c1ee6b16941cc3104149ca307b58b41cc208293941ec59cc10524f598138b9459ca3073549292728c1ee6b149414839ca307b9ac5a9283948314e5183dcd62d4941cc520c419ca307b9ac5a92839883104139460f7358b4a0e6188209ca307b58b41cc20827283d8b3982093d66045ca2c60e6a9252460f7358a4a0a41c60f7358b52507290628c1ee6b16a4a0e6290620c60f7358b52507314831041183dcd62d4941cc4188208c1ee6b16941cc31041183dac5a0e6104107b1673040f5980e515cd524a47358a4a0a41b9ac5a92839483139ac5a928398a41882e6b16a4a0e629062081cd62d4941cc520c41039ac5a928398831040e6b16941cc31040d62d073082062ce608166028aa4948a4a0a41a9283948312928398a41882a4a0e6290620814941cc520c4102928398a41882052507310620812839862081073082039820300a5214832906229062094831040520c41014831040520c4101062080620804100400

theorem positiveNodes_checked : FKLMeta.walk (fun i v => Bool.and (Nat.beq v.parent (FKL.lane positiveP 7 i))
    (Bool.and (Nat.beq v.child (FKL.lane positiveC 6 i)) (Nat.beq v.localChild (FKL.lane positiveL 5 i)))) positiveNodes 0 = true := by
  decide +kernel

theorem positiveNode_eq (i : Fin 945) :
    positiveNode i = ⟨FKL.lane positiveP 7 i.val, FKL.lane positiveC 6 i.val, FKL.lane positiveL 5 i.val⟩ := by
  have hi : i.val < positiveNodes.length := by rw [positiveNodes_length]; exact i.isLt
  have e := FKLMeta.walk_sound _ _ 0 positiveNodes_checked i.val hi
  simp only [Nat.zero_add, Bool.and_eq_true, Nat.beq_eq] at e
  unfold positiveNode
  rw [← e.1, ← e.2.1, ← e.2.2]

def zeroP : ℕ := 0xd1a3467cf9f3e6cd9b365cb972e5c993264c98f1e3c78f162c58b162c3870e1c387060c183060bf7efdfbf7ef5ebd7af5ebd76eddbb76eddb972e5cb972e5bb76eddbb76ed5ab56ad5ab566cd9b366cd9b362c58b162c58b15ebd7af5ebd7af5ab56ad5ab56ad56ad5ab56ad5ab52a54a952a54a94e9d3a74e9d3a74e9d2a54a952a54a952a5468d1a3468d1a3468d0a142850a142850a13e7cf9f3e7cf9f3e7ce9d3a74e9d3a74e9d366cd9b366cd9b366cc993264c993264c992e5cb972e5cb972e5cb952a54a952a54a952a54993264c993264c9932644891224489122448911e3c78f1e3c78f1e3c78d1a3468d1a3468d1a3458b162c58b162c58b122448912244890e1c3870e1c3870e1c2850a142850a142850a0c183060c183060c18302040810204081020407efdfbf7efdfbf7efdfbe7cf9f3e7cf9f3e7cf9ebd7af5ebd7af5ebd78f1e3c78f1e3c76eddbb76eddba74e9d3a74e9d3972e5cb972e5cb972e1c3870e1c3870e1c386eddbb76eddbb76eddbb66cd9b366cd9b366cd9ab56ad5ab56ad5ab56ad1a3468d1a3468d1a3366cd9b366cd9b264c993264c98b162c58b160c183060c182f5ebd7af5ebd7ae5cb972e5cb972e5cb56ad5ab56ad5ab56ad58b162c58b162c58b162b56ad5ab56ad5ab56ad52a54a952a54a952a52a54a952a54a950a142850a14274e9d3a74e993264c992a54a952a548912244891223468d1a3468d1a24489122448912244850a142850a142850a140810204081020408101f3e7cf9f3e7cf9f3e78f1e3c78f1e3c74e9d3a74e9d3870e1c3870d9b366cd9a3468d193264c993060c183060b972e5cb972e58b162c58b162c54a952a54a952a54a942850a142850a142850993264c993264c99324489122448912224489122448902040810203c78f1e3c70e1c3868d1a3060c182c58b162c50a142850a12244891224488102040810204070e1c3870e1c3870e183060c183060c183050a142850a1428408102040810183060c183040810204040810200000
def zeroC : ℕ := 0xb2baacaeaa6caea9ecaeaa66b2baa99ecaea9e3b2baa99a2b2baa99e6b2baa99e3b2baa78deb2baa99a276caeaa679a2b2baa99e68ecaeaa678deb2baa78de62caeaa6689d5ecaeaa679a276caeaa679a38acaeaa679a37acaeaa678de62caea9e379846caeaa6689d5d01ecaeaa679a27571acaeaa679a389d16caeaa679a389e12caeaa679a37980ecaeaa678de6110acaea9e379844906baa99a27574081ebaa99e689d5d01c6aeaa679a389d5c616baa99e68e279d144aeaa679a389e6040ebaa99e68de6110c2aeaa678de61124206baa78de6112410299a27574081e99e689d5d02071a99e68e2757407185a679a389e7571851299e68e279d605103a679a389e6111030a99e68de611243081a678de6112420409e37984490409a27574081e689d5d02071a68e27574081c61668e279d5d01c61449a389e7585c61440e68e279d6111440c29a389e6112440c20668de61124308102379844908102379844904089d5d020789d5d02071a27574081c616279d5d020718512279d61740718510389e7585d11851030a279d61124510308189e6112440c20407984490c204079844908101e61124101d5d02077574081c67574081c615d5d020718511d6174081c61440dd6174501c61440c27585d12461440c205d6112451030810184491030810184490c20406112420406112410174081d74081c65d02071855d02071851174081c61440d74502071851030974502471851030815d12461440c20404491440c20404491030810112430810112420404490404081d02071902071854081c61444081c61440d02071851030902481c61440c20502471851030810091851030810091440c20402440c2040243081009081009040
def zeroL : ℕ := 0xbdab7b5697b5677b5692bdab49ded59c6f6ad250bdab49caf6ad271bdab38bef6ad25075ed5a4e50bdab49ca37b56938bef6ace2f6ded5a4a0e65ed5a4e5075ed5a4e5185ed5a4e517ded5a4e2f6ded59c5ed5ded5a4a0e628f7b5693941cc35ed5a4e51838b7b56939460f25ed5a4e517b477b56938bdab15ed59c5ed5a436ad250731483dab49ca0e628e6b56939460e618b6ad2728c1ee292d5a4e5183da41dab49ca2f6ac62b56938bdab48836ace2f6ad2105250731483d2728398a41cd49ca3073147316939460f730c5252728c1ee69483a4e5183dab20c549ca2f6ad23106938bdab488209c5ed5a420941cc520f28398a41cd28c1cc520e62ca307b98a398a49460f73586290728c1ee6aca418a5183dab490620ca2f6ad23104117b569104117b5690820e629078398a41cd073148398b07b98a41cc5241ee6b1473148383dcd62cc520c507b9ab494831060f6ad24188207b569188207b5691040f6ad210398a41dcc520e673148398ae629073148e6b148398a41b9ac5a8e6290627358b498a41882e6ad2520c410356920c4103569188206ad22081ab4840c520ec520e6629073158a41cc523148398a41b16a41cc520c4c5a927314831058b498a4188205a4a4188205a4831040b48c4102d2208169081483a9073290731548398a4520e62906a41cc520c4a4a0e6290620a9273148310409314831040929062081241882048c410244102420

theorem zeroNodes_checked : FKLMeta.walk (fun i v => Bool.and (Nat.beq v.parent (FKL.lane zeroP 7 i))
    (Bool.and (Nat.beq v.child (FKL.lane zeroC 6 i)) (Nat.beq v.localChild (FKL.lane zeroL 5 i)))) zeroNodes 0 = true := by
  decide +kernel

theorem zeroNode_eq (i : Fin 840) :
    zeroNode i = ⟨FKL.lane zeroP 7 i.val, FKL.lane zeroC 6 i.val, FKL.lane zeroL 5 i.val⟩ := by
  have hi : i.val < zeroNodes.length := by rw [zeroNodes_length]; exact i.isLt
  have e := FKLMeta.walk_sound _ _ 0 zeroNodes_checked i.val hi
  simp only [Nat.zero_add, Bool.and_eq_true, Nat.beq_eq] at e
  unfold zeroNode
  rw [← e.1, ← e.2.1, ← e.2.2]

def colT4 : ℕ := 0xa0706

theorem colT4_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colT4 8 i)) (childColumns 4 true) 0 = true := by
  decide +kernel

theorem colT4_len : (childColumns 4 true).length = 3 := by decide +kernel

theorem colT4_get (i : ℕ) (hi : i < 3) : (childColumns 4 true)[i]? = some (FKL.lane colT4 8 i) := by
  have hi' : i < (childColumns 4 true).length := by rw [colT4_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colT4_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

def colF4 : ℕ := 0xe0d0c0b0908050403020100

theorem colF4_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colF4 8 i)) (childColumns 4 false) 0 = true := by
  decide +kernel

theorem colF4_len : (childColumns 4 false).length = 12 := by decide +kernel

theorem colF4_get (i : ℕ) (hi : i < 12) : (childColumns 4 false)[i]? = some (FKL.lane colF4 8 i) := by
  have hi' : i < (childColumns 4 false).length := by rw [colF4_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colF4_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

def colT8 : ℕ := 0x28252421201f1c1b1a1916151413120f0e0d0c0b0a

theorem colT8_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colT8 8 i)) (childColumns 8 true) 0 = true := by
  decide +kernel

theorem colT8_len : (childColumns 8 true).length = 21 := by decide +kernel

theorem colT8_get (i : ℕ) (hi : i < 21) : (childColumns 8 true)[i]? = some (FKL.lane colT8 8 i) := by
  have hi' : i < (childColumns 8 true).length := by rw [colT8_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colT8_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

def colF8 : ℕ := 0x2c2b2a29272623221e1d1817111009080706050403020100

theorem colF8_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colF8 8 i)) (childColumns 8 false) 0 = true := by
  decide +kernel

theorem colF8_len : (childColumns 8 false).length = 24 := by decide +kernel

theorem colF8_get (i : ℕ) (hi : i < 24) : (childColumns 8 false)[i]? = some (FKL.lane colF8 8 i) := by
  have hi' : i < (childColumns 8 false).length := by rw [colF8_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colF8_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

def colT16 : ℕ := 0x9491908d8c8b888786858281807f7e7b7a79787776737271706f6e6d6a69686766656463605f5e5d5c5b5a59585554535251504f4e4d4c494847464544434241403f3c3b3a3938373635343332312e2d2c2b2a29282726252423221f1e1d1c1b1a1918171615141312

theorem colT16_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colT16 8 i)) (childColumns 16 true) 0 = true := by
  decide +kernel

theorem colT16_len : (childColumns 16 true).length = 105 := by decide +kernel

theorem colT16_get (i : ℕ) (hi : i < 105) : (childColumns 16 true)[i]? = some (FKL.lane colT16 8 i) := by
  have hi' : i < (childColumns 16 true).length := by rw [colT16_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colT16_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

def colF16 : ℕ := 0x9897969593928f8e8a8984837d7c75746c6b626157564b4a3e3d302f212011100f0e0d0c0b0a09080706050403020100

theorem colF16_checked : FKLMeta.walk (fun i v => Nat.beq v (FKL.lane colF16 8 i)) (childColumns 16 false) 0 = true := by
  decide +kernel

theorem colF16_len : (childColumns 16 false).length = 48 := by decide +kernel

theorem colF16_get (i : ℕ) (hi : i < 48) : (childColumns 16 false)[i]? = some (FKL.lane colF16 8 i) := by
  have hi' : i < (childColumns 16 false).length := by rw [colF16_len]; exact hi
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 colF16_checked i hi')
  rw [Nat.zero_add] at e
  rw [List.getElem?_eq_getElem hi', e]

end FKLMeta.Nodes
