module

public import FKLMeta.Walk
public import FKLBridge.Split

/-! Every row of `IndexedCertificateRows.split` satisfies a raw test `q`, checked by one walk over the
literal parts `SplitCertificateData.Part###.rows`. Generated by `gen_walks.py`. -/

@[expose] public section

namespace FKLMeta.SpWalk

open MatrixBounds.Numeric
set_option maxRecDepth 100000

/-- Walk all 87 literal parts. -/
def allRows (q : Nat → SplitRow → Bool) : Bool :=
  Bool.and (walk q SplitCertificateData.Part000.rows 0)
    (Bool.and (walk q SplitCertificateData.Part001.rows 64)
    (Bool.and (walk q SplitCertificateData.Part002.rows 128)
    (Bool.and (walk q SplitCertificateData.Part003.rows 192)
    (Bool.and (walk q SplitCertificateData.Part004.rows 256)
    (Bool.and (walk q SplitCertificateData.Part005.rows 320)
    (Bool.and (walk q SplitCertificateData.Part006.rows 384)
    (Bool.and (walk q SplitCertificateData.Part007.rows 448)
    (Bool.and (walk q SplitCertificateData.Part008.rows 512)
    (Bool.and (walk q SplitCertificateData.Part009.rows 576)
    (Bool.and (walk q SplitCertificateData.Part010.rows 640)
    (Bool.and (walk q SplitCertificateData.Part011.rows 704)
    (Bool.and (walk q SplitCertificateData.Part012.rows 768)
    (Bool.and (walk q SplitCertificateData.Part013.rows 832)
    (Bool.and (walk q SplitCertificateData.Part014.rows 896)
    (Bool.and (walk q SplitCertificateData.Part015.rows 960)
    (Bool.and (walk q SplitCertificateData.Part016.rows 1024)
    (Bool.and (walk q SplitCertificateData.Part017.rows 1088)
    (Bool.and (walk q SplitCertificateData.Part018.rows 1152)
    (Bool.and (walk q SplitCertificateData.Part019.rows 1216)
    (Bool.and (walk q SplitCertificateData.Part020.rows 1280)
    (Bool.and (walk q SplitCertificateData.Part021.rows 1344)
    (Bool.and (walk q SplitCertificateData.Part022.rows 1408)
    (Bool.and (walk q SplitCertificateData.Part023.rows 1472)
    (Bool.and (walk q SplitCertificateData.Part024.rows 1536)
    (Bool.and (walk q SplitCertificateData.Part025.rows 1600)
    (Bool.and (walk q SplitCertificateData.Part026.rows 1664)
    (Bool.and (walk q SplitCertificateData.Part027.rows 1728)
    (Bool.and (walk q SplitCertificateData.Part028.rows 1792)
    (Bool.and (walk q SplitCertificateData.Part029.rows 1856)
    (Bool.and (walk q SplitCertificateData.Part030.rows 1920)
    (Bool.and (walk q SplitCertificateData.Part031.rows 1984)
    (Bool.and (walk q SplitCertificateData.Part032.rows 2048)
    (Bool.and (walk q SplitCertificateData.Part033.rows 2112)
    (Bool.and (walk q SplitCertificateData.Part034.rows 2176)
    (Bool.and (walk q SplitCertificateData.Part035.rows 2240)
    (Bool.and (walk q SplitCertificateData.Part036.rows 2304)
    (Bool.and (walk q SplitCertificateData.Part037.rows 2368)
    (Bool.and (walk q SplitCertificateData.Part038.rows 2432)
    (Bool.and (walk q SplitCertificateData.Part039.rows 2496)
    (Bool.and (walk q SplitCertificateData.Part040.rows 2560)
    (Bool.and (walk q SplitCertificateData.Part041.rows 2624)
    (Bool.and (walk q SplitCertificateData.Part042.rows 2688)
    (Bool.and (walk q SplitCertificateData.Part043.rows 2752)
    (Bool.and (walk q SplitCertificateData.Part044.rows 2816)
    (Bool.and (walk q SplitCertificateData.Part045.rows 2880)
    (Bool.and (walk q SplitCertificateData.Part046.rows 2944)
    (Bool.and (walk q SplitCertificateData.Part047.rows 3008)
    (Bool.and (walk q SplitCertificateData.Part048.rows 3072)
    (Bool.and (walk q SplitCertificateData.Part049.rows 3136)
    (Bool.and (walk q SplitCertificateData.Part050.rows 3200)
    (Bool.and (walk q SplitCertificateData.Part051.rows 3264)
    (Bool.and (walk q SplitCertificateData.Part052.rows 3328)
    (Bool.and (walk q SplitCertificateData.Part053.rows 3392)
    (Bool.and (walk q SplitCertificateData.Part054.rows 3456)
    (Bool.and (walk q SplitCertificateData.Part055.rows 3520)
    (Bool.and (walk q SplitCertificateData.Part056.rows 3584)
    (Bool.and (walk q SplitCertificateData.Part057.rows 3648)
    (Bool.and (walk q SplitCertificateData.Part058.rows 3712)
    (Bool.and (walk q SplitCertificateData.Part059.rows 3776)
    (Bool.and (walk q SplitCertificateData.Part060.rows 3840)
    (Bool.and (walk q SplitCertificateData.Part061.rows 3904)
    (Bool.and (walk q SplitCertificateData.Part062.rows 3968)
    (Bool.and (walk q SplitCertificateData.Part063.rows 4032)
    (Bool.and (walk q SplitCertificateData.Part064.rows 4096)
    (Bool.and (walk q SplitCertificateData.Part065.rows 4160)
    (Bool.and (walk q SplitCertificateData.Part066.rows 4224)
    (Bool.and (walk q SplitCertificateData.Part067.rows 4288)
    (Bool.and (walk q SplitCertificateData.Part068.rows 4352)
    (Bool.and (walk q SplitCertificateData.Part069.rows 4416)
    (Bool.and (walk q SplitCertificateData.Part070.rows 4480)
    (Bool.and (walk q SplitCertificateData.Part071.rows 4544)
    (Bool.and (walk q SplitCertificateData.Part072.rows 4608)
    (Bool.and (walk q SplitCertificateData.Part073.rows 4672)
    (Bool.and (walk q SplitCertificateData.Part074.rows 4736)
    (Bool.and (walk q SplitCertificateData.Part075.rows 4800)
    (Bool.and (walk q SplitCertificateData.Part076.rows 4864)
    (Bool.and (walk q SplitCertificateData.Part077.rows 4928)
    (Bool.and (walk q SplitCertificateData.Part078.rows 4992)
    (Bool.and (walk q SplitCertificateData.Part079.rows 5056)
    (Bool.and (walk q SplitCertificateData.Part080.rows 5120)
    (Bool.and (walk q SplitCertificateData.Part081.rows 5184)
    (Bool.and (walk q SplitCertificateData.Part082.rows 5248)
    (Bool.and (walk q SplitCertificateData.Part083.rows 5312)
    (Bool.and (walk q SplitCertificateData.Part084.rows 5376)
    (Bool.and (walk q SplitCertificateData.Part085.rows 5440)
    (walk q SplitCertificateData.Part086.rows 5504))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

theorem allRows_sound (q : Nat → SplitRow → Bool) (h : allRows q = true) :
    ∀ r : Fin 5542, q r.val (IndexedCertificateRows.split r).val = true := by
  simp only [allRows, Bool.and_eq_true] at h
  obtain ⟨h000, h001, h002, h003, h004, h005, h006, h007, h008, h009, h010, h011, h012, h013, h014, h015, h016, h017, h018, h019, h020, h021, h022, h023, h024, h025, h026, h027, h028, h029, h030, h031, h032, h033, h034, h035, h036, h037, h038, h039, h040, h041, h042, h043, h044, h045, h046, h047, h048, h049, h050, h051, h052, h053, h054, h055, h056, h057, h058, h059, h060, h061, h062, h063, h064, h065, h066, h067, h068, h069, h070, h071, h072, h073, h074, h075, h076, h077, h078, h079, h080, h081, h082, h083, h084, h085, h086⟩ := h
  have P0 : ∀ r < 0, ∀ hr : r < 5542, q r (IndexedCertificateRows.split ⟨r, hr⟩).val = true :=
    FKLBridge.Rows.range_zero
  have P1 := FKLBridge.Rows.range_step 0 64 64 rfl P0 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch000 j hj hr]; exact walk_sound q _ 0 h000 j _)
  have P2 := FKLBridge.Rows.range_step 64 64 128 rfl P1 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch001 j hj hr]; exact walk_sound q _ 64 h001 j _)
  have P3 := FKLBridge.Rows.range_step 128 64 192 rfl P2 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch002 j hj hr]; exact walk_sound q _ 128 h002 j _)
  have P4 := FKLBridge.Rows.range_step 192 64 256 rfl P3 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch003 j hj hr]; exact walk_sound q _ 192 h003 j _)
  have P5 := FKLBridge.Rows.range_step 256 64 320 rfl P4 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch004 j hj hr]; exact walk_sound q _ 256 h004 j _)
  have P6 := FKLBridge.Rows.range_step 320 64 384 rfl P5 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch005 j hj hr]; exact walk_sound q _ 320 h005 j _)
  have P7 := FKLBridge.Rows.range_step 384 64 448 rfl P6 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch006 j hj hr]; exact walk_sound q _ 384 h006 j _)
  have P8 := FKLBridge.Rows.range_step 448 64 512 rfl P7 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch007 j hj hr]; exact walk_sound q _ 448 h007 j _)
  have P9 := FKLBridge.Rows.range_step 512 64 576 rfl P8 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch008 j hj hr]; exact walk_sound q _ 512 h008 j _)
  have P10 := FKLBridge.Rows.range_step 576 64 640 rfl P9 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch009 j hj hr]; exact walk_sound q _ 576 h009 j _)
  have P11 := FKLBridge.Rows.range_step 640 64 704 rfl P10 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch010 j hj hr]; exact walk_sound q _ 640 h010 j _)
  have P12 := FKLBridge.Rows.range_step 704 64 768 rfl P11 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch011 j hj hr]; exact walk_sound q _ 704 h011 j _)
  have P13 := FKLBridge.Rows.range_step 768 64 832 rfl P12 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch012 j hj hr]; exact walk_sound q _ 768 h012 j _)
  have P14 := FKLBridge.Rows.range_step 832 64 896 rfl P13 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch013 j hj hr]; exact walk_sound q _ 832 h013 j _)
  have P15 := FKLBridge.Rows.range_step 896 64 960 rfl P14 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch014 j hj hr]; exact walk_sound q _ 896 h014 j _)
  have P16 := FKLBridge.Rows.range_step 960 64 1024 rfl P15 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch015 j hj hr]; exact walk_sound q _ 960 h015 j _)
  have P17 := FKLBridge.Rows.range_step 1024 64 1088 rfl P16 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch016 j hj hr]; exact walk_sound q _ 1024 h016 j _)
  have P18 := FKLBridge.Rows.range_step 1088 64 1152 rfl P17 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch017 j hj hr]; exact walk_sound q _ 1088 h017 j _)
  have P19 := FKLBridge.Rows.range_step 1152 64 1216 rfl P18 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch018 j hj hr]; exact walk_sound q _ 1152 h018 j _)
  have P20 := FKLBridge.Rows.range_step 1216 64 1280 rfl P19 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch019 j hj hr]; exact walk_sound q _ 1216 h019 j _)
  have P21 := FKLBridge.Rows.range_step 1280 64 1344 rfl P20 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch020 j hj hr]; exact walk_sound q _ 1280 h020 j _)
  have P22 := FKLBridge.Rows.range_step 1344 64 1408 rfl P21 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch021 j hj hr]; exact walk_sound q _ 1344 h021 j _)
  have P23 := FKLBridge.Rows.range_step 1408 64 1472 rfl P22 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch022 j hj hr]; exact walk_sound q _ 1408 h022 j _)
  have P24 := FKLBridge.Rows.range_step 1472 64 1536 rfl P23 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch023 j hj hr]; exact walk_sound q _ 1472 h023 j _)
  have P25 := FKLBridge.Rows.range_step 1536 64 1600 rfl P24 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch024 j hj hr]; exact walk_sound q _ 1536 h024 j _)
  have P26 := FKLBridge.Rows.range_step 1600 64 1664 rfl P25 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch025 j hj hr]; exact walk_sound q _ 1600 h025 j _)
  have P27 := FKLBridge.Rows.range_step 1664 64 1728 rfl P26 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch026 j hj hr]; exact walk_sound q _ 1664 h026 j _)
  have P28 := FKLBridge.Rows.range_step 1728 64 1792 rfl P27 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch027 j hj hr]; exact walk_sound q _ 1728 h027 j _)
  have P29 := FKLBridge.Rows.range_step 1792 64 1856 rfl P28 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch028 j hj hr]; exact walk_sound q _ 1792 h028 j _)
  have P30 := FKLBridge.Rows.range_step 1856 64 1920 rfl P29 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch029 j hj hr]; exact walk_sound q _ 1856 h029 j _)
  have P31 := FKLBridge.Rows.range_step 1920 64 1984 rfl P30 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch030 j hj hr]; exact walk_sound q _ 1920 h030 j _)
  have P32 := FKLBridge.Rows.range_step 1984 64 2048 rfl P31 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch031 j hj hr]; exact walk_sound q _ 1984 h031 j _)
  have P33 := FKLBridge.Rows.range_step 2048 64 2112 rfl P32 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch032 j hj hr]; exact walk_sound q _ 2048 h032 j _)
  have P34 := FKLBridge.Rows.range_step 2112 64 2176 rfl P33 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch033 j hj hr]; exact walk_sound q _ 2112 h033 j _)
  have P35 := FKLBridge.Rows.range_step 2176 64 2240 rfl P34 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch034 j hj hr]; exact walk_sound q _ 2176 h034 j _)
  have P36 := FKLBridge.Rows.range_step 2240 64 2304 rfl P35 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch035 j hj hr]; exact walk_sound q _ 2240 h035 j _)
  have P37 := FKLBridge.Rows.range_step 2304 64 2368 rfl P36 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch036 j hj hr]; exact walk_sound q _ 2304 h036 j _)
  have P38 := FKLBridge.Rows.range_step 2368 64 2432 rfl P37 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch037 j hj hr]; exact walk_sound q _ 2368 h037 j _)
  have P39 := FKLBridge.Rows.range_step 2432 64 2496 rfl P38 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch038 j hj hr]; exact walk_sound q _ 2432 h038 j _)
  have P40 := FKLBridge.Rows.range_step 2496 64 2560 rfl P39 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch039 j hj hr]; exact walk_sound q _ 2496 h039 j _)
  have P41 := FKLBridge.Rows.range_step 2560 64 2624 rfl P40 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch040 j hj hr]; exact walk_sound q _ 2560 h040 j _)
  have P42 := FKLBridge.Rows.range_step 2624 64 2688 rfl P41 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch041 j hj hr]; exact walk_sound q _ 2624 h041 j _)
  have P43 := FKLBridge.Rows.range_step 2688 64 2752 rfl P42 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch042 j hj hr]; exact walk_sound q _ 2688 h042 j _)
  have P44 := FKLBridge.Rows.range_step 2752 64 2816 rfl P43 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch043 j hj hr]; exact walk_sound q _ 2752 h043 j _)
  have P45 := FKLBridge.Rows.range_step 2816 64 2880 rfl P44 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch044 j hj hr]; exact walk_sound q _ 2816 h044 j _)
  have P46 := FKLBridge.Rows.range_step 2880 64 2944 rfl P45 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch045 j hj hr]; exact walk_sound q _ 2880 h045 j _)
  have P47 := FKLBridge.Rows.range_step 2944 64 3008 rfl P46 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch046 j hj hr]; exact walk_sound q _ 2944 h046 j _)
  have P48 := FKLBridge.Rows.range_step 3008 64 3072 rfl P47 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch047 j hj hr]; exact walk_sound q _ 3008 h047 j _)
  have P49 := FKLBridge.Rows.range_step 3072 64 3136 rfl P48 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch048 j hj hr]; exact walk_sound q _ 3072 h048 j _)
  have P50 := FKLBridge.Rows.range_step 3136 64 3200 rfl P49 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch049 j hj hr]; exact walk_sound q _ 3136 h049 j _)
  have P51 := FKLBridge.Rows.range_step 3200 64 3264 rfl P50 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch050 j hj hr]; exact walk_sound q _ 3200 h050 j _)
  have P52 := FKLBridge.Rows.range_step 3264 64 3328 rfl P51 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch051 j hj hr]; exact walk_sound q _ 3264 h051 j _)
  have P53 := FKLBridge.Rows.range_step 3328 64 3392 rfl P52 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch052 j hj hr]; exact walk_sound q _ 3328 h052 j _)
  have P54 := FKLBridge.Rows.range_step 3392 64 3456 rfl P53 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch053 j hj hr]; exact walk_sound q _ 3392 h053 j _)
  have P55 := FKLBridge.Rows.range_step 3456 64 3520 rfl P54 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch054 j hj hr]; exact walk_sound q _ 3456 h054 j _)
  have P56 := FKLBridge.Rows.range_step 3520 64 3584 rfl P55 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch055 j hj hr]; exact walk_sound q _ 3520 h055 j _)
  have P57 := FKLBridge.Rows.range_step 3584 64 3648 rfl P56 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch056 j hj hr]; exact walk_sound q _ 3584 h056 j _)
  have P58 := FKLBridge.Rows.range_step 3648 64 3712 rfl P57 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch057 j hj hr]; exact walk_sound q _ 3648 h057 j _)
  have P59 := FKLBridge.Rows.range_step 3712 64 3776 rfl P58 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch058 j hj hr]; exact walk_sound q _ 3712 h058 j _)
  have P60 := FKLBridge.Rows.range_step 3776 64 3840 rfl P59 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch059 j hj hr]; exact walk_sound q _ 3776 h059 j _)
  have P61 := FKLBridge.Rows.range_step 3840 64 3904 rfl P60 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch060 j hj hr]; exact walk_sound q _ 3840 h060 j _)
  have P62 := FKLBridge.Rows.range_step 3904 64 3968 rfl P61 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch061 j hj hr]; exact walk_sound q _ 3904 h061 j _)
  have P63 := FKLBridge.Rows.range_step 3968 64 4032 rfl P62 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch062 j hj hr]; exact walk_sound q _ 3968 h062 j _)
  have P64 := FKLBridge.Rows.range_step 4032 64 4096 rfl P63 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch063 j hj hr]; exact walk_sound q _ 4032 h063 j _)
  have P65 := FKLBridge.Rows.range_step 4096 64 4160 rfl P64 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch064 j hj hr]; exact walk_sound q _ 4096 h064 j _)
  have P66 := FKLBridge.Rows.range_step 4160 64 4224 rfl P65 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch065 j hj hr]; exact walk_sound q _ 4160 h065 j _)
  have P67 := FKLBridge.Rows.range_step 4224 64 4288 rfl P66 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch066 j hj hr]; exact walk_sound q _ 4224 h066 j _)
  have P68 := FKLBridge.Rows.range_step 4288 64 4352 rfl P67 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch067 j hj hr]; exact walk_sound q _ 4288 h067 j _)
  have P69 := FKLBridge.Rows.range_step 4352 64 4416 rfl P68 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch068 j hj hr]; exact walk_sound q _ 4352 h068 j _)
  have P70 := FKLBridge.Rows.range_step 4416 64 4480 rfl P69 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch069 j hj hr]; exact walk_sound q _ 4416 h069 j _)
  have P71 := FKLBridge.Rows.range_step 4480 64 4544 rfl P70 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch070 j hj hr]; exact walk_sound q _ 4480 h070 j _)
  have P72 := FKLBridge.Rows.range_step 4544 64 4608 rfl P71 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch071 j hj hr]; exact walk_sound q _ 4544 h071 j _)
  have P73 := FKLBridge.Rows.range_step 4608 64 4672 rfl P72 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch072 j hj hr]; exact walk_sound q _ 4608 h072 j _)
  have P74 := FKLBridge.Rows.range_step 4672 64 4736 rfl P73 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch073 j hj hr]; exact walk_sound q _ 4672 h073 j _)
  have P75 := FKLBridge.Rows.range_step 4736 64 4800 rfl P74 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch074 j hj hr]; exact walk_sound q _ 4736 h074 j _)
  have P76 := FKLBridge.Rows.range_step 4800 64 4864 rfl P75 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch075 j hj hr]; exact walk_sound q _ 4800 h075 j _)
  have P77 := FKLBridge.Rows.range_step 4864 64 4928 rfl P76 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch076 j hj hr]; exact walk_sound q _ 4864 h076 j _)
  have P78 := FKLBridge.Rows.range_step 4928 64 4992 rfl P77 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch077 j hj hr]; exact walk_sound q _ 4928 h077 j _)
  have P79 := FKLBridge.Rows.range_step 4992 64 5056 rfl P78 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch078 j hj hr]; exact walk_sound q _ 4992 h078 j _)
  have P80 := FKLBridge.Rows.range_step 5056 64 5120 rfl P79 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch079 j hj hr]; exact walk_sound q _ 5056 h079 j _)
  have P81 := FKLBridge.Rows.range_step 5120 64 5184 rfl P80 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch080 j hj hr]; exact walk_sound q _ 5120 h080 j _)
  have P82 := FKLBridge.Rows.range_step 5184 64 5248 rfl P81 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch081 j hj hr]; exact walk_sound q _ 5184 h081 j _)
  have P83 := FKLBridge.Rows.range_step 5248 64 5312 rfl P82 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch082 j hj hr]; exact walk_sound q _ 5248 h082 j _)
  have P84 := FKLBridge.Rows.range_step 5312 64 5376 rfl P83 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch083 j hj hr]; exact walk_sound q _ 5312 h083 j _)
  have P85 := FKLBridge.Rows.range_step 5376 64 5440 rfl P84 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch084 j hj hr]; exact walk_sound q _ 5376 h084 j _)
  have P86 := FKLBridge.Rows.range_step 5440 64 5504 rfl P85 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch085 j hj hr]; exact walk_sound q _ 5440 h085 j _)
  have P87 := FKLBridge.Rows.range_step 5504 38 5542 rfl P86 (fun j hj hr => by
    rw [FKLBridge.Split.dispatch086 j hj hr]; exact walk_sound q _ 5504 h086 j _)
  intro r
  exact P87 r.val r.isLt r.isLt

end FKLMeta.SpWalk
