module

public import FKLMeta.Shapes
public import FKLMeta.Walk
public import DyadicOrbitSupport
public import VerifiedOrbitSupportTables

/-! Raw support checks of sparse orbit rows against the coarse orbit totals `OrbitLevelN.totalAt`
(packed into 5-bit lanes). Generated by `gen_support.py`. -/

@[expose] public section

namespace FKLMeta.Support

open MatrixBounds.Numeric

/-- `OrbitLevel2.totalAt` on its 6 orbits, 5-bit lanes. -/
def total2 : ℕ := 0x8310820

theorem total2_checked : FKLMeta.walk (fun c v => Nat.beq v (FKL.lane total2 5 c)) OrbitLevel2.totalTable.toList 0 = true := by
  decide +kernel

theorem total2_len : OrbitLevel2.totalTable.toList.length = 6 := by decide +kernel

theorem total2_eq : ∀ c < 6, OrbitLevel2.totalAt c = FKL.lane total2 5 c := by
  intro c hc
  have hc' : c < OrbitLevel2.totalTable.toList.length := by rw [total2_len]; exact hc
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 total2_checked c hc')
  rw [Nat.zero_add] at e
  unfold OrbitLevel2.totalAt
  rw [← Array.getElem?_toList, List.getElem?_eq_getElem hc', Option.getD_some, e]

/-- `OrbitLevel3.totalAt` on its 21 orbits, 5-bit lanes. -/
def total3 : ℕ := 0x8398c5218a4214831888310820

theorem total3_checked : FKLMeta.walk (fun c v => Nat.beq v (FKL.lane total3 5 c)) OrbitLevel3.totalTable.toList 0 = true := by
  decide +kernel

theorem total3_len : OrbitLevel3.totalTable.toList.length = 21 := by decide +kernel

theorem total3_eq : ∀ c < 21, OrbitLevel3.totalAt c = FKL.lane total3 5 c := by
  intro c hc
  have hc' : c < OrbitLevel3.totalTable.toList.length := by rw [total3_len]; exact hc
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 total3_checked c hc')
  rw [Nat.zero_add] at e
  unfold OrbitLevel3.totalAt
  rw [← Array.getElem?_toList, List.getElem?_eq_getElem hc', Option.getD_some, e]

/-- `OrbitLevel4.totalAt` on its 231 orbits, 5-bit lanes. -/
def total4 : ℕ := 0x41ee7358e6b18d62d6a62d4a4a1cd6316a6358b5a92b5316a5250a4a18b52928525086b16b5256a4a54c5a949429284250b525283a5073a0e65a92941d2839d0731949420e641cc6398a52316a5250a4a10941ce642d494a0e941ce8398c539949420e641cc6398a5218a45250839907318e6294862908941ce629cc5298a420ca418c48398c5218a4214831888310820

theorem total4_checked : FKLMeta.walk (fun c v => Nat.beq v (FKL.lane total4 5 c)) OrbitLevel4.totalTable.toList 0 = true := by
  decide +kernel

theorem total4_len : OrbitLevel4.totalTable.toList.length = 231 := by decide +kernel

theorem total4_eq : ∀ c < 231, OrbitLevel4.totalAt c = FKL.lane total4 5 c := by
  intro c hc
  have hc' : c < OrbitLevel4.totalTable.toList.length := by rw [total4_len]; exact hc
  have e := Nat.eq_of_beq_eq_true (FKLMeta.walk_sound _ _ 0 total4_checked c hc')
  rw [Nat.zero_add] at e
  unfold OrbitLevel4.totalAt
  rw [← Array.getElem?_toList, List.getElem?_eq_getElem hc', Option.getD_some, e]

/-- Every sparse column is below `W` and has coarse total `target` in the packed table `T`. -/
def supF (T W target : ℕ) (es : List (ℕ × ℕ)) : Bool :=
  List.rec (motive := fun _ => Bool) true
    (fun e _ acc => Bool.and (Bool.and (Nat.blt e.1 W) (Nat.beq (FKL.lane T 5 e.1) target)) acc) es

theorem supF_sound (T W target : ℕ) (stat : ℕ → ℕ) (hs : ∀ c < W, stat c = FKL.lane T 5 c) :
    ∀ es : List (ℕ × ℕ), supF T W target es = true → es.all (fun e => decide (stat e.1 = target)) = true := by
  intro es
  induction es with
  | nil => intro _; rfl
  | cons e es ih =>
    intro h
    change Bool.and (Bool.and (Nat.blt e.1 W) (Nat.beq (FKL.lane T 5 e.1) target)) (supF T W target es) = true at h
    simp only [Bool.and_eq_true, Nat.blt_eq, Nat.beq_eq] at h
    simp only [List.all_cons, Bool.and_eq_true, decide_eq_true_eq]
    exact ⟨by rw [hs _ h.1.1]; exact h.1.2, ih h.2⟩

theorem supportCheck_of (T W target : ℕ) (stat : ℕ → ℕ) (hs : ∀ c < W, stat c = FKL.lane T 5 c)
    (row : DyadicRow) (h : supF T W target row.entries = true) : row.supportCheck stat target = true :=
  supF_sound T W target stat hs row.entries h

/-- Fast form of the zero-registry row test. -/
def zeroRowF (code : ℕ) (row : DyadicRow) : Bool :=
  cond (Nat.beq code 0) true
    (cond (Nat.beq row.width 6) (supF total2 6 (Nat.sub code 1) row.entries)
    (cond (Nat.beq row.width 21) (supF total3 21 (Nat.sub code 1) row.entries)
    (cond (Nat.beq row.width 231) (supF total4 231 (Nat.sub code 1) row.entries) false)))

theorem zeroRow_sound (code : ℕ) (row : DyadicRow) (h : zeroRowF code row = true) :
    (if code = 0 then true
    else if row.width = 6 then row.supportCheck OrbitLevel2.totalAt (code-1)
    else if row.width = 21 then row.supportCheck OrbitLevel3.totalAt (code-1)
    else if row.width = 231 then row.supportCheck OrbitLevel4.totalAt (code-1)
    else false) = true := by
  unfold zeroRowF at h
  cases h0 : Nat.beq code 0
  · rw [h0, cond_false] at h
    rw [if_neg (Nat.ne_of_beq_eq_false h0)]
    cases h6 : Nat.beq row.width 6
    · rw [h6, cond_false] at h
      rw [if_neg (Nat.ne_of_beq_eq_false h6)]
      cases h21 : Nat.beq row.width 21
      · rw [h21, cond_false] at h
        rw [if_neg (Nat.ne_of_beq_eq_false h21)]
        cases h231 : Nat.beq row.width 231
        · rw [h231, cond_false] at h; exact absurd h (by simp)
        · rw [h231, cond_true] at h
          rw [if_pos (Nat.eq_of_beq_eq_true h231)]
          exact supportCheck_of _ _ _ _ total4_eq row h
      · rw [h21, cond_true] at h
        rw [if_pos (Nat.eq_of_beq_eq_true h21)]
        exact supportCheck_of _ _ _ _ total3_eq row h
    · rw [h6, cond_true] at h
      rw [if_pos (Nat.eq_of_beq_eq_true h6)]
      exact supportCheck_of _ _ _ _ total2_eq row h
  · rw [if_pos (Nat.eq_of_beq_eq_true h0)]

end FKLMeta.Support
