module

public import SuppliedDimensionCertificateTable1
public import FKLDimData.C1Check00
public import FKLDimData.C1Check01

@[expose] public section

namespace MatrixBounds.Numeric.FKLDimData.C1

set_option maxRecDepth 100000

theorem reads : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.table 0 :=
  (FKLCert.rawReads_append 44 220 KW MW tree ((((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part000).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part001).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part002))))).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part003).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part004).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part005)))))) ((((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part006).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part007).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part008))))).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part009).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part010).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part011)))))) 0
    (FKLCert.rawReads_append 44 220 KW MW tree ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part000).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part001).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part002)))) ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part003).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part004).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part005)))) 0
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part000 ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part001).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part002)) 0
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block000.terms _ 0 8 (by decide) part000 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part000 0)
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part001 MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part002 512
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block001.terms _ 8 8 (by decide) part001 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part001 512)
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block002.terms _ 16 8 (by decide) part002 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part002 1024)))
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part003 ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part004).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part005)) 1536
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block003.terms _ 24 8 (by decide) part003 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part003 1536)
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part004 MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part005 2048
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block004.terms _ 32 8 (by decide) part004 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part004 2048)
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block005.terms _ 40 8 (by decide) part005 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part005 2560))))
    (FKLCert.rawReads_append 44 220 KW MW tree ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part006).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part007).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part008)))) ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part009).append (((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part010).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part011)))) 3072
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part006 ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part007).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part008)) 3072
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block006.terms _ 48 8 (by decide) part006 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part006 3072)
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part007 MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part008 3584
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block007.terms _ 56 8 (by decide) part007 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part007 3584)
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block008.terms _ 64 8 (by decide) part008 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part008 4096)))
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part009 ((MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part010).append (MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part011)) 4608
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block009.terms _ 72 8 (by decide) part009 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part009 4608)
    (FKLCert.rawReads_append 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part010 MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part011 5120
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block010.terms _ 80 8 (by decide) part010 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part010 5120)
    (FKLCert.rawReads_ofList 44 220 KW MW tree RateCertificateData.Dimension1Block011.terms _ 88 6 (by decide) part011 : FKLCert.RawReads 44 220 KW MW tree MatrixBounds.Numeric.SuppliedDimensionRates.SuppliedDimensionCertificateTable1.part011 5632)))))

end MatrixBounds.Numeric.FKLDimData.C1
