module

public import FKLMeta.Flat
public import FKLBridge.Idx.DyadicZero4

/-! Flat copy of `MatrixBounds.Numeric.ParameterIndexData.DyadicZero4.table` (generated by `gen_flat.py`). -/

@[expose] public section

namespace FKLMeta.Flat.DyadicZero4

/-- All 1 chunks of `FKLBridge.Idx.DyadicZero4.tree`, 896 bits each. -/
def flat : ℕ := 0xee0fb92ee4bbaceeafbaaeea7ba8ee9fba6ee97ba4ee8fba2ee87ba0ee7fb9eee77b9cee6fb9aee67b98ee5fb96ee57b94ee4fb84ee13b83ee4bb91ee43b8fee3bb8dee33b8bee2bb89ee23b87ee1bb85ee13b83

theorem flat_checked : FKLMeta.flatOk FKLBridge.Idx.DyadicZero4.tree 896 flat 1 = true := by decide +kernel

theorem get_eq (i : Fin 48) : (MatrixBounds.Numeric.ParameterIndexData.DyadicZero4.table.get i).val = FKL.lane flat 14 i.val := by
  rw [FKLBridge.Idx.DyadicZero4.get_eq]
  exact FKLMeta.flat_get FKLBridge.Idx.DyadicZero4.tree 6 14 flat 1 flat_checked i.val (by have := i.isLt; omega)

end FKLMeta.Flat.DyadicZero4
