module

public import FKLMeta.Flat
public import FKLBridge.Idx.SplitAlpha4

/-! Flat copy of `MatrixBounds.Numeric.ParameterIndexData.SplitAlpha4.table` (generated by `gen_flat.py`). -/

@[expose] public section

namespace FKLMeta.Flat.SplitAlpha4

/-- All 1 chunks of `FKLBridge.Idx.SplitAlpha4.tree`, 1664 bits each. -/
def flat : ℕ := 0x15a5ad2568eb455a1ad0567eb3d59dace566eb35599acc565eb2d595aca564eb25591ac8563eb1d58dac6562eb15589ac4561eb0d585ac2560eb05581ac055feafd57dabe55eeaf5579abc55deaed575aba55ceae5571ab855beadd56dab655aead5569ab4559eacd565ab2558eac5561ab0557eabd55daae556eab5559aac555eaad555aaa554eaa5551aa8553ea9d54daa6552ea95549aa4551ea8d545aa2550ea85541aa054fea7d53d

theorem flat_checked : FKLMeta.flatOk FKLBridge.Idx.SplitAlpha4.tree 1664 flat 1 = true := by decide +kernel

theorem get_eq (i : Fin 105) : (MatrixBounds.Numeric.ParameterIndexData.SplitAlpha4.table.get i).val = FKL.lane flat 13 i.val := by
  rw [FKLBridge.Idx.SplitAlpha4.get_eq]
  exact FKLMeta.flat_get FKLBridge.Idx.SplitAlpha4.tree 7 13 flat 1 flat_checked i.val (by have := i.isLt; omega)

end FKLMeta.Flat.SplitAlpha4
