module

public import RateCertificateData.Level30Block000
public import RateCertificateData.Level30Block001
public import RateCertificateData.Level30Block002
public import RateCertificateData.Level30Block003
public import RateCertificateData.Level30Block004
public import RateCertificateData.Level30Block005
public import RateCertificateData.Level30Block006
public import RateCertificateData.Level30Block007
public import RateCertificateData.Level30Block008
public import RateCertificateData.Level30Block009
public import RateCertificateData.Level30Block010
public import RateCertificateData.Level30Block011
public import RateCertificateData.Level30Block012
public import RateCertificateData.Level30Block013
public import RateCertificateData.Level30Block014
public import RateCertificateData.Level30Block015
public import RateCertificateData.Level30Block016
public import RateCertificateData.Level30Block017
public import RateCertificateData.Level30Block018
public import RateCertificateData.Level30Block019
public import RateCertificateData.Level30Block020
public import RateCertificateData.Level30Block021
public import RateCertificateData.Level30Block022
public import RateCertificateData.Level30Block023
public import RateCertificateData.Level30Block024
public import RateCertificateData.Level30Block025
public import RateCertificateData.Level30Block026
public import RateCertificateData.Level30Block027
public import RateCertificateData.Level30Block028
public import RateCertificateData.Level30Block029
public import RateCertificateData.Level30Block030
public import RateCertificateData.Level30Block031
public import RateCertificateData.Level30Block032
public import RateCertificateData.Level30Block033
public import RateCertificateData.Level30Block034
public import RateCertificateData.Level30Block035
public import RateCertificateData.Level30Block036
public import RateCertificateData.Level30Block037
public import RateCertificateData.Level30Block038
public import RateCertificateData.Level30Block039
public import RateCertificateData.Level30Block040
public import RateCertificateData.Level30Block041
public import RateCertificateData.Level30Block042
public import RateCertificateData.Level30Block043
public import RateCertificateData.Level30Block044
public import RateCertificateData.Level30Block045
public import RateCertificateData.Level30Block046
public import RateCertificateData.Level30Block047
public import RateCertificateData.Level30Block048
public import RateCertificateData.Level30Block049
public import RateCertificateData.Level30Block050
public import RateCertificateData.Level30Block051
public import RateCertificateData.Level30Block052
public import RateCertificateData.Level30Block053
public import RateCertificateData.Level30Block054
public import RateCertificateData.Level30Block055
public import RateCertificateData.Level30Block056
public import RateCertificateData.Level30Block057
public import RateCertificateData.Level30Block058
public import RateCertificateData.Level30Block059
public import RateCertificateData.Level30Block060
public import RateCertificateData.Level30Block061
public import RateCertificateData.Level30Block062
public import RateCertificateData.Level30Block063
public import RateCertificateData.Level30Block064
public import RateCertificateData.Level30Block065
public import RateCertificateData.Level30Block066
public import RateCertificateData.Level30Block067
public import RateCertificateData.Level30Block068
public import RateCertificateData.Level30Block069
public import RateCertificateData.Level30Block070
public import RateCertificateData.Level30Block071
public import RateCertificateData.Level30Block072
public import RateCertificateData.Level30Block073
public import RateCertificateData.Level30Block074
public import RateCertificateData.Level30Block075
public import RateCertificateData.Level30Block076
public import RateCertificateData.Level30Block077
public import RateCertificateData.Level30Block078
public import RateCertificateData.Level30Block079
public import RateCertificateData.Level30Block080
public import RateCertificateData.Level30Block081
public import RateCertificateData.Level30Block082
public import RateCertificateData.Level30Block083
public import RateCertificateData.Level30Block084
public import RateCertificateData.Level30Block085
public import RateCertificateData.Level30Block086
public import RateCertificateData.Level30Block087
public import RateCertificateData.Level30Block088
public import RateCertificateData.Level30Block089
public import RateCertificateData.Level30Block090
public import RateCertificateData.Level30Block091
public import RateCertificateData.Level30Block092
public import RateCertificateData.Level30Block093
public import RateCertificateData.Level30Block094
public import RateCertificateData.Level30Block095
public import RateCertificateData.Level30Block096
public import RateCertificateData.Level30Block097
public import RateCertificateData.Level30Block098
public import RateCertificateData.Level30Block099
public import RateCertificateData.Level30Block100
public import RateCertificateData.Level30Block101
public import RateCertificateData.Level30Block102
public import RateCertificateData.Level30Block103
public import RateCertificateData.Level30Block104
public import RateCertificateData.Level30Block105
public import RateCertificateData.Level30Block106
public import RateCertificateData.Level30Block107
public import RateCertificateData.Level30Block108
public import RateCertificateData.Level30Block109
public import RateCertificateData.Level30Block110
public import RateCertificateData.Level30Block111
public import RateCertificateData.Level30Block112
public import RateCertificateData.Level30Block113
public import RateCertificateData.Level30Block114
public import RateCertificateData.Level30Block115
public import RateCertificateData.Level30Block116
public import RateCertificateData.Level30Block117
public import RateCertificateData.Level30Block118
public import RateCertificateData.Level30Block119
public import RateCertificateData.Level30Block120
public import RateCertificateData.Level30Block121
public import RateCertificateData.Level30Block122
public import RateCertificateData.Level30Block123
public import RateCertificateData.Level30Block124
public import RateCertificateData.Level30Block125
public import RateCertificateData.Level30Block126
public import RateCertificateData.Level30Block127
public import RateCertificateData.Level30Block128
public import RateCertificateData.Level30Block129
public import RateCertificateData.Level30Block130
public import RateCertificateData.Level30Block131
public import RateCertificateData.Level30Block132
public import RateCertificateData.Level30Block133
public import RateCertificateData.Level30Block134
public import RateCertificateData.Level30Block135

@[expose] public section
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option backward.dsimp.instances true

namespace MatrixBounds.Numeric.CertifiedLevel3Rate0
set_option maxRecDepth 100000
set_option maxHeartbeats 32000000

/-- All exact expression blocks, in their complete original order. -/
def blocks : List CertifiedLogBlock := [
  RateCertificateData.Level30Block000.certificate, RateCertificateData.Level30Block001.certificate, RateCertificateData.Level30Block002.certificate, RateCertificateData.Level30Block003.certificate, RateCertificateData.Level30Block004.certificate, RateCertificateData.Level30Block005.certificate, RateCertificateData.Level30Block006.certificate, RateCertificateData.Level30Block007.certificate, RateCertificateData.Level30Block008.certificate, RateCertificateData.Level30Block009.certificate, RateCertificateData.Level30Block010.certificate, RateCertificateData.Level30Block011.certificate, RateCertificateData.Level30Block012.certificate, RateCertificateData.Level30Block013.certificate, RateCertificateData.Level30Block014.certificate, RateCertificateData.Level30Block015.certificate, RateCertificateData.Level30Block016.certificate, RateCertificateData.Level30Block017.certificate, RateCertificateData.Level30Block018.certificate, RateCertificateData.Level30Block019.certificate, RateCertificateData.Level30Block020.certificate, RateCertificateData.Level30Block021.certificate, RateCertificateData.Level30Block022.certificate, RateCertificateData.Level30Block023.certificate, RateCertificateData.Level30Block024.certificate, RateCertificateData.Level30Block025.certificate, RateCertificateData.Level30Block026.certificate, RateCertificateData.Level30Block027.certificate, RateCertificateData.Level30Block028.certificate, RateCertificateData.Level30Block029.certificate, RateCertificateData.Level30Block030.certificate, RateCertificateData.Level30Block031.certificate, RateCertificateData.Level30Block032.certificate, RateCertificateData.Level30Block033.certificate, RateCertificateData.Level30Block034.certificate, RateCertificateData.Level30Block035.certificate, RateCertificateData.Level30Block036.certificate, RateCertificateData.Level30Block037.certificate, RateCertificateData.Level30Block038.certificate, RateCertificateData.Level30Block039.certificate, RateCertificateData.Level30Block040.certificate, RateCertificateData.Level30Block041.certificate, RateCertificateData.Level30Block042.certificate, RateCertificateData.Level30Block043.certificate, RateCertificateData.Level30Block044.certificate, RateCertificateData.Level30Block045.certificate, RateCertificateData.Level30Block046.certificate, RateCertificateData.Level30Block047.certificate, RateCertificateData.Level30Block048.certificate, RateCertificateData.Level30Block049.certificate, RateCertificateData.Level30Block050.certificate, RateCertificateData.Level30Block051.certificate, RateCertificateData.Level30Block052.certificate, RateCertificateData.Level30Block053.certificate, RateCertificateData.Level30Block054.certificate, RateCertificateData.Level30Block055.certificate, RateCertificateData.Level30Block056.certificate, RateCertificateData.Level30Block057.certificate, RateCertificateData.Level30Block058.certificate, RateCertificateData.Level30Block059.certificate, RateCertificateData.Level30Block060.certificate, RateCertificateData.Level30Block061.certificate, RateCertificateData.Level30Block062.certificate, RateCertificateData.Level30Block063.certificate, RateCertificateData.Level30Block064.certificate, RateCertificateData.Level30Block065.certificate, RateCertificateData.Level30Block066.certificate, RateCertificateData.Level30Block067.certificate, RateCertificateData.Level30Block068.certificate, RateCertificateData.Level30Block069.certificate, RateCertificateData.Level30Block070.certificate, RateCertificateData.Level30Block071.certificate, RateCertificateData.Level30Block072.certificate, RateCertificateData.Level30Block073.certificate, RateCertificateData.Level30Block074.certificate, RateCertificateData.Level30Block075.certificate, RateCertificateData.Level30Block076.certificate, RateCertificateData.Level30Block077.certificate, RateCertificateData.Level30Block078.certificate, RateCertificateData.Level30Block079.certificate, RateCertificateData.Level30Block080.certificate, RateCertificateData.Level30Block081.certificate, RateCertificateData.Level30Block082.certificate, RateCertificateData.Level30Block083.certificate, RateCertificateData.Level30Block084.certificate, RateCertificateData.Level30Block085.certificate, RateCertificateData.Level30Block086.certificate, RateCertificateData.Level30Block087.certificate, RateCertificateData.Level30Block088.certificate, RateCertificateData.Level30Block089.certificate, RateCertificateData.Level30Block090.certificate, RateCertificateData.Level30Block091.certificate, RateCertificateData.Level30Block092.certificate, RateCertificateData.Level30Block093.certificate, RateCertificateData.Level30Block094.certificate, RateCertificateData.Level30Block095.certificate, RateCertificateData.Level30Block096.certificate, RateCertificateData.Level30Block097.certificate, RateCertificateData.Level30Block098.certificate, RateCertificateData.Level30Block099.certificate, RateCertificateData.Level30Block100.certificate, RateCertificateData.Level30Block101.certificate, RateCertificateData.Level30Block102.certificate, RateCertificateData.Level30Block103.certificate, RateCertificateData.Level30Block104.certificate, RateCertificateData.Level30Block105.certificate, RateCertificateData.Level30Block106.certificate, RateCertificateData.Level30Block107.certificate, RateCertificateData.Level30Block108.certificate, RateCertificateData.Level30Block109.certificate, RateCertificateData.Level30Block110.certificate, RateCertificateData.Level30Block111.certificate, RateCertificateData.Level30Block112.certificate, RateCertificateData.Level30Block113.certificate, RateCertificateData.Level30Block114.certificate, RateCertificateData.Level30Block115.certificate, RateCertificateData.Level30Block116.certificate, RateCertificateData.Level30Block117.certificate, RateCertificateData.Level30Block118.certificate, RateCertificateData.Level30Block119.certificate, RateCertificateData.Level30Block120.certificate, RateCertificateData.Level30Block121.certificate, RateCertificateData.Level30Block122.certificate, RateCertificateData.Level30Block123.certificate, RateCertificateData.Level30Block124.certificate, RateCertificateData.Level30Block125.certificate, RateCertificateData.Level30Block126.certificate, RateCertificateData.Level30Block127.certificate, RateCertificateData.Level30Block128.certificate, RateCertificateData.Level30Block129.certificate, RateCertificateData.Level30Block130.certificate, RateCertificateData.Level30Block131.certificate, RateCertificateData.Level30Block132.certificate, RateCertificateData.Level30Block133.certificate, RateCertificateData.Level30Block134.certificate, RateCertificateData.Level30Block135.certificate
]
/-- Complete real logarithmic expression; the `Supplied*Certified*` modules identify it with the actual tensor-pipeline rate. -/
noncomputable def value : ℝ := certifiedBlocksValue blocks
/-- Exact integer enclosure of the complete expression at scale 2^60. -/
def bounds : FixedBounds := ⟨1764618995536380219, 1764618995538572731⟩
/-- All block endpoint sums agree exactly with the reported complete rate interval. -/
theorem bounds_checked : certifiedBlocksBounds blocks = bounds := by decide +kernel
/-- The reported interval contains the complete exact real logarithmic expression. -/
theorem sound : (bounds.interval (2^60)).Contains value :=
  certifiedBlocks_sound blocks bounds bounds_checked

end MatrixBounds.Numeric.CertifiedLevel3Rate0
